<div style="text-align: center; margin-top: 120px;">

  <h2><strong>Universidad de Costa Rica</strong></h2>
  <h3>Departamento de Ciencias Actuariales</h3>
  <h3>Herramientas para Ciencia de Datos II</h3>
  
  <div style="height: 30px;"></div>
  
  <h2><strong>Bitácora 2</strong></h2>
  
  <div style="height: 30px;"></div>

  <h3>Profesor:</h3>
  <h3>Joshua Cervantes Artavia</h3>

  <div style="height: 30px;"></div>

  <h3>Estudiantes:</h3>

  <div style="font-size: 20px; line-height: 1;">
    Alexandra González Bermúdez, C4F535<br><br>
    Daniela Prado Vargas, C26070<br><br>
    Emily Estefanía Mora Contreras, C4H522<br><br>
    Liz de María Salazar Amaya, C4J618<br><br>
    Erika Wu Liang, C38600
  </div>

  <div style="height: 30px;"></div>

  <h3>Primer Semestre</h3>
  <h3>2026</h3>
  
  <div style="height: 30px;"></div>

</div>

# Enlace del repositorio de GitHub <br>

https://github.com/ErikaW23/Herramientas-2

# Indicación general <br>

Desarrolle el siguiente módulo de la página PaperCode: *Fundamentos de redes neuronales*. Explique las ideas principales de la fundamentación teórico matemática con sus propias palabras. 

# Ejercicio 1: capa lineal hacia adelante <br>

Implemente la función linear_forward(X, W, b), la cual  implemente el paso hacia adelante de una capa lineal. 

**Operación matemática:** Y = XW + b, donde: 

- X es la matriz de entrada de tamaño (N, D(in)) <br>
- W es la matriz de pesos de tamaño (D(in), D(out)) <br>
- b es el vector de sesgo de la forma (D(out), ) <br>
- Y es la matriz resultante de tamaño (N, D(out)) <br>

*Requerimientos* 

1. Use la multiplicación matricial (@ or np.dot) para XW. <br>
2. Use broadcasting para la suma del vector del sesgo. <br>
3. Retorne un resultado de tamaño (N, D(out)). <br>
4. Maneje los lotes de forma eficiente: de manera vectorizada, sin usar ciclos. <br>
5. Asegúrese de que las dimensiones sean compatibles: D(in) debe coincidir entre X y W. 

### Explicación de la fundamentación matemática 

La operación matemática a realizar es la siguiente: 

$$ 
Y = XW + b
$$

Se detalla a continuación la fundamentación matemática detrás de la operación señalada: <br>

1. *Multiplicación matricial*: el primer elemento de la operación corresponde a una multiplicación matricial. Con tal de que sea posible multiplicar dos matrices, es necesario que el número de columnas de la primera matriz coincida con el número de filas de la segunda matriz, además, en ese sentido, es importante recordar que la multiplicación de matrices no es una operación conmutativa, es decir, el orden de los elementos en la multiplicación sí importa y su intercambio no produce el mismo resultado. En general: 
$$ 
XW \neq WX
$$

**Nota**: al ser X de dimensiones (N, D(in)) y W de dimensiones (D(in), D(out)), la matriz resultado de la multiplicación tendrá dimensiones (N, D(out)). <br>

2. *Suma de un vector a una matriz*: para sumar un vector a una matriz, es necesario que las dimensiones del vector coincidan con las dimensiones de la matriz. En este caso, el vector es de la forma (D(out), ): un vector conformado por D(out) elementos. El broadcasting ejecutado por Numpy, permite expandir las dimensiones del vector de manera que sea posible efectuar la suma entre el vector y la matriz: convierte el vector en una matriz cuyo número de filas coincide con el número de filas de la matriz con la que se está sumando, además, cada fila está conformada por los elementos del vector. Numpy puede efectuar el broadcasting exitosamente dado que el número de elementos del vector coincide con el número de columnas de la matriz con la que se está sumando, de manera que el vector posee una dimensión compatible para realizar broadcasting. 

In [4]:
#Se importa Numpy para la realización de operaciones vectorizadas.
import numpy as np 

#Se crea la función:
def linear_forward(X, W, b): 
    #Para asegurarse que las matrices y el vector sean arreglos de Numpy: 
    X = np.array(X)
    W = np.array(W)
    b = np.array(b)

    _, columnas_X = X.shape
    filas_W , _ = W.shape
    
    #Se verifica que las dimensiones de las matrices coincidan para realizar la operación.
    if columnas_X == filas_W: 
        #Se multiplican las matrices.
        multiplicacion_matrices = np.dot(X, W)
        #Se suma el vector de sesgo con broadcasting.
        resultado = multiplicacion_matrices + b
        return resultado
    
    #En caso de que las dimensiones no coincidan. 
    else: 
        return "Las dimensiones de las matrices no coinciden"

#Se prueban los ejemplos. 
print(linear_forward([[1, 2]], [[1, 0], [0, 1]], [1, 1]))
print(linear_forward([[1, 2, 3], [4, 5, 6]], [[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]], [1.0, 2.0]))

[[2 3]]
[[3.2 4.8]
 [5.9 8.4]]


# Ejercicio 2: capa lineal hacia atrás <br>

Dada la operación ya conocida: Y = XW + b; implemente la función linear_backward(dout, X, W, b) que calcule los gradientes durante la retropropagación. <br>
**Nota**: dout representa el gradiente de tamaño (N, D(out)): 
$$ 
\frac{∂L}{∂Y}
$$ 

Se debe retornar un diccionario con los siguientes gradientes: 

1. dx. Con la fórmula dada por: 
$$ 
\frac{∂L}{∂X}  = \frac{∂L}{∂Y} ⋅ W^{T} = dout ⋅ W^{T}
$$

2. dw. Con la fórmula dada por: 
$$ 
\frac{∂L}{∂W}  = X^{T} ⋅ \frac{∂L}{∂Y} =  X^{T} ⋅ dout
$$

3. db. Con la fórmula dada por: 
$$ 
\frac{∂L}{∂b}  = \sum_{i=1}^{N} \frac{∂L}{∂Y_{i}} = \sum_{filas} dout
$$

*Requerimientos*

1. Utilice la multiplicación matricial para los cálculos de dx y dw. <br>
2. Use sum a lo largo de la dimensión de los lotes (axis = 0), para db. <br>
3. Retorne un diccionario con claves: dx, dw y db. <br>
4. Asegúrese de que las dimensiones de salida coincidan con las dimensiones de entrada. <br>
5. Use operaciones vectorizadas: no ciclos explícitos. <br>

### Explicación de la fundamentación matemática <br>

En primera instancia, note que dout representa cómo cambia la pérdida L respecto a cada elemento de la salida Y. Así los componentes de dout indican cuánto cambiaría la pérdida si se modificara la salida correspondiente en Y, donde Y = XW + b. En el backward pass, se recorre el sentido contrario: se pretende "repartir" la responsabilidad de los cambios, entre los elementos que participaron al momento de producir Y: X, W y b. <br>

En segunda instancia, es importante entender qué representa cada uno de los gradientes calculados. <br>

1. **dx = ∂L/∂X**. Representa cómo cambian los valores de la pérdida cuando cambian los valores de X, donde X corresponde a la matriz del tensor de entrada. Recuerde que en Y, X participa de la forma XW, así, la contribución en la pérdida por parte de las entradas de la matriz del tensor, está determinada por los valores de los pesos que las acompañan, en este caso los valores W. En vista de lo anterior, una vez conocidas las contribuciones en la pérdida por parte de las salidas Y, es necesario distribuir dichos valores entre las entradas X con tal de obtener dx. De esta forma aparece la transpuesta W, pues constituye la manera matricial de recorrer esas mismas conexiones en el sentido opuesto. 

2.  **dw = ∂L/∂W**. Representa cómo cambian los valores de la pérdida cuando cambian los valores de W, donde W corresponde a la matriz de pesos. Recuerde que en Y, W participa de la forma XW, de forma que cada peso controla cuánto influye una entrada específica en una salida específica. Puesto que ya se conocen las contribuciones en la pérdida por parte de las salidas Y, se precisa distribuir dichos valores entre las entradas W con tal de obtener dw, así aparece la transpuesta de X, pues constituye la manera matricial de recorrer esas mismas conexiones en el sentido opuesto.

3. **db = ∂L/∂b**. Representa cómo cambian los valores de la pérdida cuando cambian los valores de b, donde b corresponde al vector de sesgo. Recuerde que en Y, b participa de la forma: Y = XW + b, desplaza las salidas de la multiplicación matricial. Es importante comprender que en el backward pass, se pretende medir el impacto del sesgo en la pérdida, por lo que se deben considerar todas las contribuciones de todas las entradas. En vista de lo anterior, el gradiente respecto al sesgo se obtiene sumando todas las contribuciones de dout a lo largo de las entradas.


In [10]:
#Se importa Numpy
import numpy as np

#Se crea la función: 
def linear_backward(dout, X, W, b): 
    #Para asegurarse que las matrices y el vector sean arreglos de Numpy: 
    X = np.array(X)
    W = np.array(W)
    b = np.array(b)
    dout = np.array(dout)
     
    #Se crea una lista con las claves del diccionario.
    claves = ["dx", "dw", "db"]

    #Se calcula dx, usando multiplicación matricial:
    dx = np.dot(dout, W.transpose())
    #Para asegurarse de que las dimensiones coincidan:
    if dx.shape != X.shape: 
        return "Ocurrió un problema con las dimensiones de las matrices"

    #Se calcula dw, usando multiplicación matricial: 
    dw = np.dot(X.transpose(), dout)
    #Para asegurarse de que las dimensiones coincidan:
    if dw.shape != W.shape: 
        return "Ocurrió un problema con las dimensiones de las matrices"

    #Se calcula db, usando la función sum con axis=0: 
    db = np.sum(dout, axis = 0)
    #Para asegurarse de que las dimensiones coincidan:
    if db.shape != b.shape: 
        return "Ocurrió un problema con las dimensiones de las matrices"

    #Se crea una lista con los valores del diccionario. 
    gradientes = [dx, dw, db]
    
    #Se crea el diccionario. 
    diccionario_gradientes = dict(zip(claves, gradientes))

    return diccionario_gradientes

#Se prueba el ejemplo.
resultado_1 = linear_backward([[0.1, 0.2],[0.3, 0.4]], [[1, 2], [3, 4]], [[0.5, 0.6], [0.7, 0.8]], [0.1, 0.2])

for clave, valor in resultado_1.items():
    print(f"{clave}:")
    print(valor)
    print()

dx:
[[0.17 0.23]
 [0.39 0.53]]

dw:
[[1.  1.4]
 [1.4 2. ]]

db:
[0.4 0.6]



# Ejercicio 3: Paso Adelante (Forward) de la Activación ReLU<br>

Implemente la función relu_forward(x) que aplique la función de activación ReLU elemento por elemento a un tensor de entrada. El comportamiento de la función ReLU se define matemáticamente como: <br>
$$
\text{ReLU}(x) = \max(0, x) = \begin{cases} x & \text{si } x > 0 \\ 0 & \text{si } x \le 0 \end{cases}
$$

Se debe retornar un tensor de salida con el mismo tamaño y forma (shape) que el tensor de entrada x. Además, los valores positivos deben permanecer sin cambios, mientras que los valores negativos o iguales a cero deben transformarse en cero.<br>

*Requerimientos*<br>

1. Aplique ReLU elemento por elemento a todos los valores en el tensor de entrada.<br>
2. Retorne una salida que mantenga la misma forma (shape) que la entrada.<br>
3. Use operaciones vectorizadas.<br>
4. Maneje cualquier forma de entrada (puede ser un escalar, vector, matriz o un tensor de mayor dimensión).<br>
5. Preserve el dtype de entrada (o convierta al tipo de punto flotante adecuado).<br>

### Explicación de la fundamentación matemática <br>

En primera instancia, note que la función ReLU actúa como un umbral simple que preserva la forma del tensor de entrada. Los valores menores o iguales a cero son reemplazados por cero, mientras que los valores positivos se transfieren directamente a la salida sin modificación alguna. Debido a que esta operación se aplica de manera independiente sobre cada elemento del tensor, la salida conserva exactamente las mismas dimensiones y forma que el tensor de entrada (x).<br>

Además, ReLU introduce no linealidad en la red neuronal, permitiendo el aprendizaje de patrones no lineales. Sin esta característica, la combinación de múltiples capas colapsaría matemáticamente en una única capa lineal. Asimismo, al convertir los valores negativos en cero, genera activaciones dispersas, es decir, salidas con una gran cantidad de ceros. <br>

Otra propiedad importante es que, para entradas positivas, la función se comporta como una identidad, preservando los valores originales. Esto favorece el flujo del gradiente, ya que el gradiente es igual a 1 para valores positivos y 0 para valores negativos, ayudando a evitar el problema del desvanecimiento de gradientes presente en funciones de activación como la sigmoide o la tangente hiperbólica.<br>

Finalmente, ReLU destaca por su eficiencia computacional, pues su cálculo se reduce a una operación elemental que consiste en seleccionar el valor máximo entre cada elemento de entrada y cero. Gracias a esta simplicidad, resulta una función de activación rápida y ampliamente utilizada en arquitecturas modernas de aprendizaje profundo. <br>






In [ ]:
import numpy as np

def relu_forward(x):
    x = np.asarray(x)
    # Si la condición (x > 0) se cumple, mantiene x; si no, coloca 0
    y = np.where(x > 0, x, 0)
    return y

# Se prueban los ejemplos
x = [-2.0, -1.0, 0.0, 1.0, 2.0, 5.0]
print(relu_forward(x))

x = [[-1, 2, -3],
     [4, -5, 6]]
print(relu_forward(x))


[0. 0. 0. 1. 2. 5.]
[[0 2 0]
 [4 0 6]]


# Ejercicio 4: Activación ReLU hacia atrás (backward)

Dada la función relu_forward() creada en el ejercicio anterior, implementar relu_forward(dout, x) que calcule el gradiente durante la retropropagación.
De manera matemática: 
$$\frac{\partial L}{\partial X} = \frac{\partial L}{\partial Y} \cdot \frac{\partial Y}{\partial X} = \text{dout} \cdot \mathbb{I}(x > 0)$$

donde: 

- $\mathbb{I}(x > 0)$ es una función indicadora (*mask*) que vale $1$ donde $x > 0$ y $0$ en caso contrario.
- Esta es la derivada de ReLU:

$$\frac{d}{dx}\max(0, x) = \begin{cases} 1 & \text{si } x > 0 \\ 0 & \text{si } x \leq 0 \end{cases}$$

*Requirimientos* <br>
1. Usar la entrada `x` del forward para determinar qué elementos eran positivos.
2. Crear una máscara: `mask = (x > 0)` (arreglo booleano o de 0/1).
3. Multiplicar `dout` por la máscara de forma element-wise.
4. Retornar un gradiente de la misma forma que la entrada.
5. Manejar el caso borde: `x == 0` (convencionalmente se trata como gradiente $0$).
6. Usar operaciones vectorizadas (evitar loops explícitos).

### Explicación de la fundamentación matemática




In [8]:
# Se importa numpy
import numpy as np

# Se crea la función solicitada
def relu_backward(dout, x):
    x = np.asarray(x)
    dout = np.asarray(dout)
    mask = x > 0
    dx = dout * mask #los elementos negativos se convertirán en 0, y los positivos mantendrán su valor
    return dx
#Ejemplo del ejercicio anterior relu_forward()

x = [-1.0, 2.0, -3.0, 0.0, 5.0]
dout = [0.1, 0.2, 0.3, 0.4, 0.5]
print(relu_backward(dout,x))
#Ejemplo 2
x = [[-1, 2],
     [-3, 4]]

dout = [[0.1, 0.2],
        [0.3, 0.4]]
print(relu_backward(dout,x))

[0.  0.2 0.  0.  0.5]
[[0.  0.2]
 [0.  0.4]]


# Ejercicio 5: activación Sigmoide <br>

Implemente la función sigmoid_ops(x, dout) que realice tanto el paso hacia adelante (forward pass) como el paso hacia atrás (backward pass) para la función de activación sigmoide de manera numéricamente estable. La función sigmoide se define matemáticamente como: <br>
$$\sigma(x) = \frac{1}{1 + e^{-x}} = \frac{e^x}{1 + e^x}$$

Como entrada, se debe recibir un tensor $x$ de cualquier tamaño y forma, y un gradiente de la capa superior $dout$ con esa misma forma. La función debe retornar un diccionario con dos componentes que conserven las dimensiones originales de $x$: "out", que representa la salida del paso hacia adelante $\sigma(x)$ con valores acotados en el rango $(0, 1)$, y "dx", que corresponde al gradiente del paso hacia atrás $\frac{\partial L}{\partial X}$ obtenido mediante la aplicación de la regla de la cadena. <br>

*Requerimientos* <br>

1. Implemente una versión numéricamente estable que pueda manejar valores negativos grandes. <br>
2. Calcular el paso hacia adelante utilizando la fórmula $\sigma(x) = \frac{1}{1 + e^{-x}}$ o $\sigma(x) = \frac{e^x}{1 + e^x}$ según el signo de $x$.<br>
3. Calcular el paso hacia atrás utilizando la fórmula $dout \cdot \sigma(x)(1 - \sigma(x))$.<br>
4. Retornar un diccionario que contenga exclusivamente las claves "out" y "dx".<br>
5. Manejar cualquier forma de tensor de entrada (aplicando la operación elemento por elemento).<br>
6. Usar operaciones vectorizadas.<br>

### Explicación de la fundamentación matemática <br>

Inicialmente, el paso hacia adelante (forward pass) de la función sigmoide toma cualquier número real y lo comprime o "exprime" en un rango acotado entre 0 y 1, dibujando una curva suave con forma de "S" que es simétrica alrededor del punto $(0, 0.5)$. Cuando las entradas son valores positivos grandes, $\sigma(x)$ se aproxima a 1; si la entrada es cero, el resultado es exactamente 0.5; y si las entradas son valores negativos grandes, se desplazan hacia 0. <br>

 Para garantizar la estabilidad numérica en el código, se deben alternar dos fórmulas según el signo de la entrada:<br>

 - Para valores de $x$ muy positivos, $e^{-x} \approx 0$, por lo que se utiliza la forma estándar $\sigma(x) = \frac{1}{1 + e^{-x}}$.<br>

 - Para valores de $x$ muy negativos, la expresión $e^{-x}$ puede causar un desbordamiento, por lo que se debe utilizar la versión matemática equivalente $\sigma(x) = \frac{e^x}{1 + e^x}$ para mitigar este error.<br>

 En segunda instancia, el paso hacia atrás (backward pass) aprovecha una propiedad algebraica elegante de la derivada de la sigmoide:<br>

 $$\frac{d}{dx}\sigma(x) = \frac{e^{-x}}{(1 + e^{-x})^2} = \sigma(x)(1 - \sigma(x))$$
 
 Esta forma permite que el gradiente se calcule eficientemente reutilizando de manera directa la salida del paso hacia adelante, eliminando la necesidad de volver a calcular funciones exponenciales costosas. De este modo, al aplicar la regla de la cadena con el gradiente de la capa superior ($dout$), el gradiente final respecto a la entrada se determina multiplicando el gradiente entrante por la derivada local:<br>
 
 $$\frac{\partial L}{\partial X} = \frac{\partial L}{\partial Y} \cdot \sigma'(X) = dout \cdot \sigma(X)(1 - \sigma(X))$$
 
 Finalmente, el texto señala una propiedad crítica observable en esta fundamentación: el problema del desvanecimiento del gradiente (vanishing gradient problem). Cuando los valores de $x$ son muy positivos o muy negativos, la función sigmoide se satura (se aproxima a 1 o a 0). En estas regiones, la derivada $\sigma'(x) = \sigma(x)(1 - \sigma(x))$ tiende a volverse prácticamente cero, lo que causa que los gradientes finales sean extremadamente pequeños y ralentice o imposibilite el aprendizaje en las capas ocultas.<br>



# Ejercicio 7: pérdida MSE

Implemente una función mse_loss(y_pred, y_true) que calcule la pérdida de error cuadrático medio y su gradiente con respecto a las predicciones.

**Requerimientos**

1. Retornar el valor de la pérdida loss, que corresponde al promedio de los errores cuadrados.
2. Retornar el gradiente dx con respecto a y_pred.
3. Usar operaciones vectorizadas de la librería NumPy.
4. No utilizar bucles for explícitos.
5. La función debe funcionar para arreglos de tamaño (N, D), donde N representa la cantidad de observaciones y D la cantidad de variables o características.

## Explicación de la fundamentación matemática

En este ejercicio se trabaja con la función de pérdida conocida como **error cuadrático medio**, o *Mean Squared Error* por sus siglas en inglés. Esta función permite medir qué tan diferentes son los valores predichos por un modelo respecto a los valores reales.

Matemáticamente, si y_pred contiene las predicciones del modelo y y_true contiene los valores reales, primero se calcula la diferencia entre ambos arreglos:

$$
y_{pred} - y_{true}
$$

Esta diferencia representa el error de predicción para cada entrada. Luego, cada error se eleva al cuadrado:

$$
(y_{pred,ij} - y_{true,ij})^2
$$

El uso del cuadrado es importante porque elimina los signos negativos y penaliza con mayor fuerza los errores más grandes. Finalmente, se calcula el promedio de todos los errores cuadrados, tomando en cuenta las $N \cdot D$ entradas del arreglo:

$$
L = \frac{1}{N \cdot D} \sum_{i=1}^{N} \sum_{j=1}^{D} (y_{pred,ij} - y_{true,ij})^2
$$

En esta fórmula, $N$ representa la cantidad de muestras y $D$ la cantidad de características por muestra. Por lo tanto, la pérdida final es un único número escalar. Si la pérdida es cercana a cero, significa que las predicciones son muy parecidas a los valores reales. Si la pérdida es grande, significa que el modelo está cometiendo errores más altos.

Además de calcular la pérdida, también se debe calcular el gradiente con respecto a y_pred, ya que este indica cómo cambia la pérdida cuando cambian las predicciones. El gradiente está dado por:

$$
\frac{\partial L}{\partial y_{pred}} = \frac{2}{N \cdot D}(y_{pred} - y_{true})
$$

Este resultado se obtiene al derivar la función de pérdida respecto a las predicciones. En términos intuitivos, el gradiente indica la dirección en la que se debe ajustar la predicción para reducir el error. Por esta razón, es una parte fundamental en el proceso de entrenamiento de modelos mediante retropropagación.

## Explicación del código

Primero, y_pred y y_true se convierten en arreglos de Numpy para poder hacer operaciones elemento por elemento. Luego, se calcula error = y_pred - y_true, que representa la diferencia entre las predicciones y los valores reales.

Después, loss = np.mean(error ** 2) eleva cada error al cuadrado y calcula el promedio de todos esos valores. Ese resultado es la pérdida MSE. Luego, dx = (2 / y_pred.size) * error calcula el gradiente respecto a y_pred. Aquí y_pred.size es la cantidad total de elementos, equivalente a N * D.

Finalmente, la función devuelve un diccionario con "loss" y "dx", como pide el enunciado.

In [6]:
import numpy as np

def mse_loss(y_pred, y_true):
    y_pred = np.array(y_pred)
    y_true = np.array(y_true)

    error = y_pred - y_true
    loss = np.round(np.mean(error ** 2), 3)

    dx = np.round((2 / y_pred.size) * error, 3)

    return {"loss": loss, "dx": dx} #El enunciado pide devolver un diccionario

#Se prueba el ejemplo de la página de PaperCode
print(mse_loss([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[1.5, 2.0, 2.5], [3.5, 5.5, 6.5]]))

{'loss': 0.208, 'dx': array([[-0.167,  0.   ,  0.167],
       [ 0.167, -0.167, -0.167]])}


# Ejercicio 8: pérdida de entropía cruzada binaria

Implemente una función bce_loss(y_pred, y_true) que calcule la pérdida de entropía cruzada binaria y su gradiente con respecto a las predicciones.

**Requerimientos**

1. Retornar el valor de la pérdida loss, que corresponde al promedio de la entropía cruzada binaria.
2. Retornar el gradiente dx con respecto a y_pred.
3. Usar operaciones vectorizadas de la librería NumPy.
4. No utilizar bucles for explícitos.
5. La función debe funcionar para arreglos de tamaño (N,), donde N representa la cantidad de observaciones.
6. Agregar un valor pequeño epsilon para evitar problemas numéricos al calcular logaritmos.

## Explicación de la fundamentación matemática

En este ejercicio se trabaja con la función de pérdida conocida como **entropía cruzada binaria**, o *Binary Cross Entropy Loss*. Esta función se utiliza principalmente en problemas de clasificación binaria, donde cada observación pertenece a una de dos clases posibles.

En este caso, cada valor real $y_i$ puede tomar únicamente los valores 0 o 1. El valor 1 indica que la observación pertenece a la clase positiva, mientras que el valor 0 indica que pertenece a la clase negativa.

Por otro lado, y_pred contiene las probabilidades predichas por el modelo. Estas probabilidades usualmente provienen de una función sigmoide, por lo que cada valor $p_i$ se encuentra entre 0 y 1. Un valor cercano a 1 indica que el modelo cree que la observación pertenece a la clase positiva, mientras que un valor cercano a 0 indica que el modelo cree que pertenece a la clase negativa.

Matemáticamente, la pérdida se define como:

$$
L = -\frac{1}{N} \sum_{i=1}^{N} \left[y_i \log(p_i) + (1-y_i)\log(1-p_i)\right]
$$

En esta fórmula, $N$ representa la cantidad total de observaciones, $y_i$ representa la clase real de la observación $i$, y $p_i$ representa la probabilidad predicha por el modelo para esa misma observación.

La idea principal de esta función es penalizar al modelo cuando asigna baja probabilidad a la clase correcta. Por ejemplo, si la clase real es 1, se espera que la probabilidad predicha sea cercana a 1. Si la clase real es 0, se espera que la probabilidad predicha sea cercana a 0.

Cuando la predicción coincide bien con el valor real, la pérdida es pequeña. En cambio, cuando el modelo predice una probabilidad muy equivocada, la pérdida aumenta. Por esta razón, un menor valor de pérdida indica un mejor desempeño del modelo.

Además, para evitar problemas numéricos, se agrega un valor pequeño llamado epsilon dentro de los logaritmos. Esto es necesario porque el logaritmo de 0 no está definido. Entonces, en lugar de calcular directamente $\log(p_i)$ y $\log(1-p_i)$, se calcula:

$$
\log(p_i + \epsilon)
$$

y

$$
\log(1-p_i + \epsilon)
$$

donde:

$$
\epsilon = 1 \times 10^{-9}
$$

Por lo tanto, la pérdida implementada en el código queda como:

$$
L = -\frac{1}{N} \sum_{i=1}^{N} \left[y_i \log(p_i+\epsilon) + (1-y_i)\log(1-p_i+\epsilon)\right]
$$

Además de calcular la pérdida, también se calcula el gradiente con respecto a las predicciones. En este ejercicio se utiliza la forma simplificada:

$$
dx = \frac{p-y}{N}
$$

Este gradiente indica cómo deben ajustarse las predicciones para reducir la pérdida. Si la predicción es mayor que el valor real, el gradiente será positivo, lo que indica que la predicción debe disminuir. Si la predicción es menor que el valor real, el gradiente será negativo, lo que indica que la predicción debe aumentar.

## Explicación del código

# Ejercicio 13: optimizador Adam

Implemente una función adam_step(w, dw, lr, beta1, beta2, eps, t, m, v) que realice un paso del optimizador Adam para actualizar los pesos de un modelo.

**Requerimientos**

1. Actualizar el primer momento m, que funciona como un término parecido al momentum.
2. Actualizar el segundo momento v, que acumula información sobre los gradientes al cuadrado.
3. Aplicar la corrección de sesgo para m y v.
4. Actualizar los pesos w usando la regla de Adam.
5. Retornar los pesos actualizados, el nuevo primer momento y el nuevo segundo momento.
6. Usar operaciones vectorizadas de la librería NumPy.
7. No utilizar bucles for explícitos.
8. La función debe funcionar para pesos de cualquier forma, ya sean escalares, vectores o matrices.

## Explicación de la fundamentación matemática

En este ejercicio se trabaja con el optimizador **Adam**, cuyo nombre proviene de *Adaptive Moment Estimation*. Este método se utiliza para actualizar los pesos de un modelo durante el entrenamiento, combinando dos ideas importantes: el uso de momentum y el ajuste adaptativo de la tasa de aprendizaje.

En primer lugar, se tiene el peso actual del modelo, representado por w, y el gradiente de la función de pérdida con respecto a ese peso, representado por dw. El gradiente indica en qué dirección aumenta la pérdida, por lo que el optimizador actualiza los pesos en la dirección contraria para intentar reducirla.

Adam utiliza un primer momento, representado por m, que acumula un promedio móvil de los gradientes. Su actualización está dada por:

$$
m_{new} = \beta_1 m + (1-\beta_1)dw
$$

En esta expresión, $\beta_1$ controla cuánto peso se le da al momento anterior. Usualmente, este valor es cercano a 0.9. El objetivo de este término es suavizar los cambios del gradiente y conservar información de pasos anteriores.

Además, Adam utiliza un segundo momento, representado por v, que acumula un promedio móvil de los gradientes al cuadrado. Su actualización está dada por:

$$
v_{new} = \beta_2 v + (1-\beta_2)dw^2
$$

En este caso, $\beta_2$ controla cuánto peso se le da al segundo momento anterior. Usualmente, este valor es cercano a 0.999. Este término permite medir qué tan grandes han sido los gradientes recientes, lo cual ayuda a adaptar el tamaño del paso para cada parámetro.

Sin embargo, al inicio del entrenamiento, los valores de m y v normalmente empiezan en cero. Esto puede provocar que los primeros valores estén sesgados hacia cero. Por esta razón, Adam aplica una corrección de sesgo:

$$
\hat{m} = \frac{m_{new}}{1-\beta_1^{t+1}}
$$

y

$$
\hat{v} = \frac{v_{new}}{1-\beta_2^{t+1}}
$$

En estas fórmulas, t representa la iteración actual. La corrección permite compensar el efecto de haber iniciado los momentos en cero.

Finalmente, los pesos se actualizan usando la siguiente regla:

$$
w_{new} = w - \frac{lr}{\sqrt{\hat{v}}+\epsilon}\hat{m}
$$

En esta fórmula, lr representa la tasa de aprendizaje y $\epsilon$ es un valor pequeño que se agrega para evitar divisiones entre cero. El término $\sqrt{\hat{v}}+\epsilon$ permite ajustar el tamaño del paso según la magnitud de los gradientes. Si un parámetro ha tenido gradientes grandes, su actualización se reduce. Si ha tenido gradientes pequeños, puede recibir una actualización relativamente mayor.

Por esta razón, Adam es un optimizador adaptativo: no actualiza todos los pesos con el mismo tamaño de paso, sino que ajusta la actualización de acuerdo con el comportamiento de cada parámetro.

## Explicación del código

# Ejercicio 14: inicialización de los pesos <br>

Implemente la función xavier_init(dimensión), que inicialice los pesos usando la inicialización uniforme Xavier/Glorot. El parámetro de la dimensión corresponde al tamaño de la matriz de pesos: una tupla de la forma (fan_in, fan_out), donde fan_in es el número de entradas a la capa y fan_out es el número de salidas de la capa. Retorne un arreglo de Numpy de tamaño (fan_in, fan_out), cuyos elementos sean pesos muestreados de la distribución uniforme Xavier. <br>

*Requerimientos* <br>

1. Calcule el límite: <br>
$$
\sqrt{\frac{6}{fan_{in}+fan_{out}}}
$$
2. Genere una muestra de la distribución uniforme: U(-límite, límite).
3. Retorne un arreglo de Numpy de las dimensiones especificadas, deben coincidir con las dimensiones del parámetro. <br>
4. Use np.random.uniform para muestrear a partir de la distribución uniforme. <br>
5. Maneje los casos límite: valores muy pequeños o valores muy grandes para fan_in y fan_out. <br>

### Explicación de la fundamentación matemática <br>

El método de inicialización de pesos de Xavier es utilizado en redes neuronales con el objetivo de resolver el problema de los gradientes que desaparecen o explotan, lo que puede dificultar el entrenamiento de redes neuronales profundas. Su objetivo consiste en mantener la varianza en los pasos forward y backward de una red neuronal. En la inicialización de Xavier, el factor clave es el número de entradas y salidas en las capas, y no tanto el método de aleatorización: se busca mantener la varianza dentro de límites que permitan un aprendizaje efectivo. <br>

Los pesos se inicializan extrayéndolos de una distribución uniforme aleatoria dentro de un rango específico que se determina mediante la fórmula:
$$
x = \sqrt{\frac{6}{n_{inputs}+n_{outputs}}}
$$
Es importante destacar que n_inputs representa el número de entradas a la capa de entrada, mientras que n_outputs representa el número de salidas de la capa de salida. De esta forma, para cada peso de la red neuronal, se extrae un valor aleatorio de una distribución uniforme en el intervalo [-x, x]; al restringir los pesos a un rango determinado por x, se garantiza que la varianza de los pesos iniciales esté controlada y sea adecuada para un entrenamiento eficaz. <br>

Por otro lado, la importancia de la inicialización de pesos se detalla a través de los siguientes tres aspectos: <br>

- *Los gradientes que desaparecen o explotan*: el problema de los gradientes que desaparecen se produce cuando los gradientes durante el entrenamiento se vuelven extremadamente pequeños, lo que provoca que la red aprenda muy lentamente o no aprenda en absoluto. Después, el problema del gradiente explosivo se produce cuando los gradientes se vuelven extremadamente grandes, lo que genera un entrenamiento inestable e ineficaz. La inicialización de pesos de Xavier resuelve este problema.  <br> <br>

- *El sobreajuste*: la inicialización de pesos ayuda indirectamente a evitar el sobreajuste: garantiza que la red neuronal comience el entrenamiento con pesos bien escalados, lo que previene ciertos problemas como el desvanecimiento de los gradientes y la saturación neuronal. <br> <br>

- *La saturación*: la saturación de las funciones de activación se refiere a una situación en la que la salida de una función de activación se aproxima extremadamente a su valor mínimo o a su valor máximo para un amplio rango de entradas. La inicialización de pesos ayuda a mantener las activaciones en un rango equilibrado, evitando la saturación y los problemas asociados a los gradientes. 

**Información tomada de:** https://www.geeksforgeeks.org/deep-learning/xavier-initialization/

In [9]:
#Se importa Numpy 
import numpy as np

#Se crea la función:
def xavier_init(dimension):
    #Se desempaquetan los valores de la tupla del parámetro.
    fan_in, fan_out = dimension

    #Se calcula el límite superior
    limite_superior = np.sqrt(6/(fan_in + fan_out))

    #Se calcula el límite inferior
    limite_inferior = -limite_superior

    #Se usa np.random.uniform para muestrear: 
    pesos = np.random.uniform(limite_inferior, limite_superior, dimension)

    return pesos 

#Se prueba el ejemplo:
print(xavier_init((100, 50)))

[[-0.02592419 -0.02756816  0.15492561 ...  0.14237864 -0.03592398
   0.01291576]
 [ 0.01967171 -0.1096332   0.04273314 ...  0.02649997 -0.03627057
  -0.05800519]
 [-0.13618146  0.06180355 -0.14704622 ... -0.10813369 -0.13149009
   0.07740274]
 ...
 [-0.0842602  -0.11407851  0.13688355 ... -0.19099123 -0.19661444
   0.05912137]
 [ 0.08776477 -0.07416845  0.10298545 ...  0.19573583 -0.05441384
   0.07361774]
 [-0.06545253  0.00430415 -0.18132035 ...  0.11829099  0.08003839
  -0.06358727]]


# Ejercicio 18: normalización de lotes hacia adelante <br>

Implemente la función batchnorm_forward(x, gamma, beta, eps=1e-5, momentum=0.9, running_mean=None, running_var=None, train=True), que realice la normalización de los lotes. Debe retornar una tupla de la forma: (out, cache, new_running_mean, new_running_var). <br>

**Entradas** <br>
- *x*: el tensor de entrada, de dimensiones (N,D). <br>
- *gamma*: el parámetro de escala, de dimensiones (D,). <br>
- *beta*: el parámetro de desplazamiento, de tamaño (D,). <br>
- *eps*: una pequeña constante orientada a brindar estabilidad numérica. <br>
- *momentum*: el momentum para estadísticas de ejecución. <br>
- *running_mean*: la media cambiante de tamaño (D,). <br>
- *running_var*: la varianza cambiante de tamaño (D,). <br>
- *train*: un booleano que posee un valor verdadero si está en entrenamiento o que posee un valor falso si está en evaluación. <br>

**Salidas** <br>
- *out*: la salida normalizada, de dimensiones (N,D). <br> 
- *cache*: un diccionario que contiene los valores requeridos para el backward pass. Debe incluir: x, x_norm, mean, var, gamma, eps.  <br>
- *new_running_mean*: media cambiante actualizada, para la próxima iteración. <br>
- *new_running_var*: varianza cambiante actualizada, para la próxima iteración. <br>

*Requerimientos*

1. Maneje el modo de entrenamiento y el modo de evaluación correctamente. <br>
2. Calcule las estadísticas a lo largo de la dimensión de los lotes (axis = 0). <br>
3. Utilice broadcasting para la sustracción de la media y la varianza. <br>
4. Actualice las estadísticas cambiantes durante el entrenamiento. <br>
5. Almacene todos los valores necesarios para el backward pass. <br>
6. Maneje la inicialización de las estadísticas cambiantes (None → ceros). <br>
7. Use operaciones vectorizadas, evitar los ciclos explícitos. <br>

### Explicación de la fundamentación matemática <br>

La normalización de lotes se emplea para mitigar el problema del desplazamiento de las covariables internas en redes neuronales. Se encarga de normalizar los datos dentro de cada sublote: calcula tanto la media como la varianza de los datos en un lote y luego ajusta los valores para que tengan un rango similar. Después, los escala y los desplaza con el objetivo de que el modelo aprenda efectivamente. <br> 

Este proceso mantiene las entradas de cada capa de la red en un rango estable, inclusive si las salidas de las capas anteriores cambian durante el entrenamiento, en consecuencuia, el entrenamiento se agiliza y adquiere mayor estabilidad. 

##### Beneficios de la normalización de lotes 
La normalización de lotes se asegura de que las salidas de cada capa se mantengan estables a medida que el modelo aprende, lo anterior ayuda al modelo a aprender con una mayor velocidad, de manera más efectiva. Se detallan a continuación algunos beneficios puntuales: <br>

- Resuelve el problema del desplazamiento de las covariables internas. <br>
- Hace que el entrenamiento sea más rápido y estable. <br>
- Permite emplear tasas de aprendizaje más altas. <br>
- Ayuda a evitar los gradientes que desaparecen o explotan. <br>
- Introduce un ligero efecto de regularización que reduce la necesidad de añadir técnicas de regularización como el dropout. <br>

**Información tomada de:** https://www.geeksforgeeks.org/deep-learning/what-is-batch-normalization-in-deep-learning/

In [7]:
#Se importa Numpy
import numpy as np 

#Se crea la función: 
def batchnorm_forward(x, gamma, beta, eps=1e-5, momentum=0.9, running_mean=None, running_var=None, train=True):

    filas, columnas = x.shape

    #Primero se inicializan las estadísticas cambiantes: 
    if running_mean is None: 
        #Dado que las estadísticas cambiantes se calculan a lo largo de las columnas. 
        running_mean = np.zeros(columnas)

    if running_var is None:
        #Dado que las estadísticas cambiantes se calculan a lo largo de las columnas.
        running_var = np.zeros(columnas)
    
    #Se maneja la fase de entrenamiento:
    if train: 
        #Se calcula la media del lote:
        media_lote = np.mean(x, axis= 0)

        #Se calcula la varianza del lote:
        varianza_lote = np.var(x, axis= 0)

        #Se normaliza: 
        x_normalizado = (x - media_lote) / np.sqrt(varianza_lote + eps)

        #Se escala y desplaza: 
        x_escalado_desplazado = gamma * x_normalizado + beta

        #Se actualizan las estadísticas cambiantes: 
        running_mean_nueva = (momentum * running_mean + (1 - momentum) * media_lote)
        running_var_nueva = (momentum * running_var + (1 - momentum) * varianza_lote)

        #Se almacenan los datos para el backward pass: 
        almacenado = {
            "x": x,
            "x_normalizado": x_normalizado,
            "media_lote": media_lote,
            "varianza_lote": varianza_lote,
            "gamma": gamma,
            "eps": eps
        }

    #Se maneja la fase de evaluación: 
    else:
        #Se utilizan las estadísticas para normalizar: 
        x_normalizado = (x - running_mean) / np.sqrt(running_var + eps)

        #Se escala y desplaza: 
        x_escalado_desplazado = gamma * x_normalizado + beta 

        #Se definen las variables en concordancia con las planteadas en el entrenamiento:
        running_mean_nueva = running_mean
        running_var_nueva = running_var

        almacenado = {
            "x": x,
            "x_normalizado": x_normalizado,
            "media_lote": running_mean,
            "varianza_lote": running_var,
            "gamma": gamma,
            "eps": eps
        }
    
    #Se retorna lo solicitado
    return x_normalizado, almacenado, running_mean_nueva, running_var_nueva

#Se prueba el ejemplo.
#Se definen las variables:
x = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
gamma = np.array([1.0, 1.0])
beta = np.array([0.0, 0.0])

#Se desempaqueta la tupla para imprimirlo ordenadamente y comparar los resultados:
salida, cache, running_mean, running_var = batchnorm_forward(x, gamma, beta, train=True)

#Se imprimen los resultados:
print("Salida:")
print(salida)

print("\nRunning mean:")
print(running_mean)

print("\nRunning var:")
print(running_var)


Salida:
[[-1.22474258 -1.22474258]
 [ 0.          0.        ]
 [ 1.22474258  1.22474258]]

Running mean:
[0.3 0.4]

Running var:
[0.26666667 0.26666667]


# Ejercicio 20: normalización de capas hacia adelante y hacia atrás

Implemente dos funciones: layernorm(x, gamma, beta, eps=1e-5) para el paso hacia adelante y layernorm_backward(dout, cache) para el paso hacia atrás de Layer Normalization.

**Requerimientos**

1. Calcular la media de cada observación usando la dimensión de características.
2. Calcular la varianza de cada observación usando la dimensión de características.
3. Normalizar cada observación de manera independiente.
4. Aplicar los parámetros gamma y beta para escalar y desplazar los datos normalizados.
5. Guardar en cache los valores necesarios para el paso hacia atrás.
6. Calcular los gradientes dx, dgamma y dbeta.
7. Usar operaciones vectorizadas de la librería NumPy.
8. No utilizar bucles for explícitos.
9. Manejar correctamente el broadcasting entre arreglos de tamaño (N,D), (N,1) y (D,).

## Explicación de la fundamentación matemática

En este ejercicio se trabaja con **Layer Normalization**, que es una técnica utilizada para normalizar las activaciones de una red neuronal. La idea principal es transformar los datos para que tengan una escala más estable durante el entrenamiento.

A diferencia de Batch Normalization, que normaliza usando información de todo el batch, Layer Normalization normaliza cada observación de manera independiente. Es decir, para cada fila de la matriz x, se calcula una media y una varianza usando sus características.

Si x tiene tamaño (N,D), entonces N representa la cantidad de observaciones y D representa la cantidad de características. Para cada observación i, se calcula primero la media:

$$
\mu_i = \frac{1}{D}\sum_{j=1}^{D}x_{ij}
$$

Esta media representa el promedio de las características de la observación i.

Luego, se calcula la varianza de esa misma observación:

$$
\sigma_i^2 = \frac{1}{D}\sum_{j=1}^{D}(x_{ij}-\mu_i)^2
$$

La varianza mide qué tan dispersos están los valores de la observación respecto a su media.

Después, cada entrada se normaliza restando la media y dividiendo entre la desviación estándar:

$$
\hat{x}_{ij} = \frac{x_{ij}-\mu_i}{\sqrt{\sigma_i^2+\epsilon}}
$$

En esta fórmula, epsilon es un valor pequeño que se agrega para evitar problemas numéricos, especialmente divisiones entre cero.

Una vez que los datos están normalizados, se aplican dos parámetros aprendibles: gamma y beta. El parámetro gamma permite escalar los valores normalizados, mientras que beta permite desplazarlos. La salida final se calcula como:

$$
y_{ij} = \gamma_j \hat{x}_{ij} + \beta_j
$$

Aquí, gamma y beta tienen tamaño (D,), porque se aplica un valor de escala y desplazamiento para cada característica.

En el paso hacia atrás, el objetivo es calcular cómo cambia la pérdida respecto a cada entrada y parámetro. Para esto, se reciben los gradientes que vienen de la siguiente capa, representados por dout.

El gradiente respecto a beta se obtiene sumando dout sobre todas las observaciones:

$$
d\beta = \sum_{i=1}^{N} dout_i
$$

El gradiente respecto a gamma se obtiene multiplicando dout por los valores normalizados y sumando sobre todas las observaciones:

$$
d\gamma = \sum_{i=1}^{N} dout_i \hat{x}_i
$$

Finalmente, el gradiente respecto a x se calcula tomando en cuenta que x participa en la media, en la varianza y en la normalización. Una forma vectorizada y eficiente de calcularlo es:

$$
dx = \frac{1}{D}\frac{1}{\sqrt{\sigma^2+\epsilon}}
\left[
D dxhat - \sum dxhat - \hat{x}\sum(dxhat \hat{x})
\right]
$$

donde:

$$
dxhat = dout \cdot \gamma
$$

Esta fórmula se aplica por cada observación, es decir, las sumas se realizan sobre la dimensión de características.

## Explicación del código