<div style="text-align: center; margin-top: 120px;">

  <h2><strong>Universidad de Costa Rica</strong></h2>
  <h3>Departamento de Ciencias Actuariales</h3>
  <h3>Herramientas para Ciencia de Datos II</h3>
  
  <div style="height: 30px;"></div>
  
  <h2><strong>Bitácora 2</strong></h2>
  
  <div style="height: 30px;"></div>

  <h3>Profesor:</h3>
  <h3>Joshua Cervantes Artavia</h3>

  <div style="height: 30px;"></div>

  <h3>Estudiantes:</h3>

  <div style="font-size: 20px; line-height: 1;">
    Alexandra González Bermúdez, C4F535<br><br>
    Daniela Prado Vargas, C26070<br><br>
    Emily Estefanía Mora Contreras, C4H522<br><br>
    Liz de María Salazar Amaya, C4J618<br><br>
    Erika Wu Liang, C38600
  </div>

  <div style="height: 30px;"></div>

  <h3>Primer Semestre</h3>
  <h3>2026</h3>
  
  <div style="height: 30px;"></div>

</div>

# Enlace del repositorio de GitHub <br>

https://github.com/ErikaW23/Herramientas-2

# Indicación general <br>

Desarrolle el siguiente módulo de la página PaperCode: *Fundamentos de redes neuronales*. Explique las ideas principales de la fundamentación teórico matemática con sus propias palabras. 

# Ejercicio 1: capa lineal hacia adelante <br>

Implemente la función linear_forward(X, W, b), la cual  implemente el paso hacia adelante de una capa lineal. 

**Operación matemática:** Y = XW + b, donde: 

- X es la matriz de entrada de tamaño (N, D(in)) <br>
- W es la matriz de pesos de tamaño (D(in), D(out)) <br>
- b es el vector de sesgo de la forma (D(out), ) <br>
- Y es la matriz resultante de tamaño (N, D(out)) <br>

*Requerimientos* 

1. Use la multiplicación matricial (@ or np.dot) para XW. <br>
2. Use broadcasting para la suma del vector del sesgo. <br>
3. Retorne un resultado de tamaño (N, D(out)). <br>
4. Maneje los lotes de forma eficiente: de manera vectorizada, sin usar ciclos. <br>
5. Asegúrese de que las dimensiones sean compatibles: D(in) debe coincidir entre X y W. 

### Explicación de la fundamentación matemática 

La operación matemática a realizar es la siguiente: 

$$ 
Y = XW + b
$$

Se detalla a continuación la fundamentación matemática detrás de la operación señalada: <br>

1. *Multiplicación matricial*: el primer elemento de la operación corresponde a una multiplicación matricial. Con tal de que sea posible multiplicar dos matrices, es necesario que el número de columnas de la primera matriz coincida con el número de filas de la segunda matriz, además, en ese sentido, es importante recordar que la multiplicación de matrices no es una operación conmutativa, es decir, el orden de los elementos en la multiplicación sí importa y su intercambio no produce el mismo resultado. En general: 
$$ 
XW \neq WX
$$

**Nota**: al ser X de dimensiones (N, D(in)) y W de dimensiones (D(in), D(out)), la matriz resultado de la multiplicación tendrá dimensiones (N, D(out)). <br>

2. *Suma de un vector a una matriz*: para sumar un vector a una matriz, es necesario que las dimensiones del vector coincidan con las dimensiones de la matriz. En este caso, el vector es de la forma (D(out), ): un vector conformado por D(out) elementos. El broadcasting ejecutado por Numpy, permite expandir las dimensiones del vector de manera que sea posible efectuar la suma entre el vector y la matriz: convierte el vector en una matriz cuyo número de filas coincide con el número de filas de la matriz con la que se está sumando, además, cada fila está conformada por los elementos del vector. Numpy puede efectuar el broadcasting exitosamente dado que el número de elementos del vector coincide con el número de columnas de la matriz con la que se está sumando, de manera que el vector posee una dimensión compatible para realizar broadcasting. 

In [4]:
#Se importa Numpy para la realización de operaciones vectorizadas.
import numpy as np 

#Se crea la función:
def linear_forward(X, W, b): 
    #Para asegurarse que las matrices y el vector sean arreglos de Numpy: 
    X = np.array(X)
    W = np.array(W)
    b = np.array(b)

    _, columnas_X = X.shape
    filas_W , _ = W.shape
    
    #Se verifica que las dimensiones de las matrices coincidan para realizar la operación.
    if columnas_X == filas_W: 
        #Se multiplican las matrices.
        multiplicacion_matrices = np.dot(X, W)
        #Se suma el vector de sesgo con broadcasting.
        resultado = multiplicacion_matrices + b
        return resultado
    
    #En caso de que las dimensiones no coincidan. 
    else: 
        return "Las dimensiones de las matrices no coinciden"

#Se prueban los ejemplos. 
print(linear_forward([[1, 2]], [[1, 0], [0, 1]], [1, 1]))
print(linear_forward([[1, 2, 3], [4, 5, 6]], [[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]], [1.0, 2.0]))

[[2 3]]
[[3.2 4.8]
 [5.9 8.4]]


# Ejercicio 2: capa lineal hacia atrás <br>

Dada la operación ya conocida: Y = XW + b; implemente la función linear_backward(dout, X, W, b) que calcule los gradientes durante la retropropagación. <br>
**Nota**: dout representa el gradiente de tamaño (N, D(out)): 
$$ 
\frac{∂L}{∂Y}
$$ 

Se debe retornar un diccionario con los siguientes tres gradientes: 

1. dx. Con la fórmula dada por: 
$$ 
\frac{∂L}{∂X}  = \frac{∂L}{∂Y} ⋅ W^{T} = dout ⋅ W^{T}
$$

2. dw. Con la fórmula dada por: 
$$ 
\frac{∂L}{∂W}  = X^{T} ⋅ \frac{∂L}{∂Y} =  X^{T} ⋅ dout
$$

3. db. Con la fórmula dada por: 
$$ 
\frac{∂L}{∂b}  = \sum_{i=1}^{N} \frac{∂L}{∂Y_{i}} = \sum_{filas} dout
$$

*Requerimientos*

1. Utilice la multiplicación matricial para los cálculos de dx y dw. <br>
2. Use sum a lo largo de la dimensión de los lotes (axis = 0), para db. <br>
3. Retorne un diccionario con claves: dx, dw y db. <br>
4. Asegúrese de que las dimensiones de salida coincidan con las dimensiones de entrada. <br>
5. Use operaciones vectorizadas: no ciclos explícitos. <br>

### Explicación de la fundamentación matemática <br>

En primera instancia, note que dout representa cómo cambia la pérdida L respecto a cada elemento de la salida Y. Así los componentes de dout indican cuánto cambiaría la pérdida si se modificara la salida correspondiente en Y, donde Y = XW + b. En el backward pass, se recorre el sentido contrario: se pretende "repartir" la responsabilidad de los cambios, entre los elementos que participaron al momento de producir Y: X, W y b. <br>

En segunda instancia, es importante entender qué representa cada uno de los gradientes calculados. <br>

1. **dx = ∂L/∂X**. Representa cómo cambian los valores de la pérdida cuando cambian los valores de X, donde X corresponde a la matriz del tensor de entrada. Recuerde que en Y, X participa de la forma XW, así, la contribución en la pérdida por parte de las entradas de la matriz del tensor, está determinada por los valores de los pesos que las acompañan, en este caso los valores W. En vista de lo anterior, una vez conocidas las contribuciones en la pérdida por parte de las salidas Y, es necesario distribuir dichos valores entre las entradas X con tal de obtener dx. De esta forma aparece la transpuesta W, pues constituye la manera matricial de recorrer esas mismas conexiones en el sentido opuesto. 

2.  **dw = ∂L/∂W**. Representa cómo cambian los valores de la pérdida cuando cambian los valores de W, donde W corresponde a la matriz de pesos. Recuerde que en Y, W participa de la forma XW, de forma que cada peso controla cuánto influye una entrada específica en una salida específica. Puesto que ya se conocen las contribuciones en la pérdida por parte de las salidas Y, se precisa distribuir dichos valores entre las entradas W con tal de obtener dw, así aparece la transpuesta de X, pues constituye la manera matricial de recorrer esas mismas conexiones en el sentido opuesto.

3. **db = ∂L/∂b**. Representa cómo cambian los valores de la pérdida cuando cambian los valores de b, donde b corresponde al vector de sesgo. Recuerde que en Y, b participa de la forma: Y = XW + b, desplaza a las salidas de la multiplicación matricial. Es importante comprender que en el backward pass, se pretende medir el impacto del sesgo en la pérdida, por lo que se deben considerar todas las contribuciones de todas las entradas. En vista de lo anterior, el gradiente respecto al sesgo se obtiene sumando todas las contribuciones de dout a lo largo de las entradas.


In [10]:
#Se importa Numpy
import numpy as np

#Se crea la función: 
def linear_backward(dout, X, W, b): 
    #Para asegurarse que las matrices y el vector sean arreglos de Numpy: 
    X = np.array(X)
    W = np.array(W)
    b = np.array(b)
    dout = np.array(dout)
     
    #Se crea una lista con las claves del diccionario.
    claves = ["dx", "dw", "db"]

    #Se calcula dx, usando multiplicación matricial:
    dx = np.dot(dout, W.transpose())
    #Para asegurarse de que las dimensiones coincidan:
    if dx.shape != X.shape: 
        return "Ocurrió un problema con las dimensiones de las matrices"

    #Se calcula dw, usando multiplicación matricial: 
    dw = np.dot(X.transpose(), dout)
    #Para asegurarse de que las dimensiones coincidan:
    if dw.shape != W.shape: 
        return "Ocurrió un problema con las dimensiones de las matrices"

    #Se calcula db, usando la función sum con axis=0: 
    db = np.sum(dout, axis = 0)
    #Para asegurarse de que las dimensiones coincidan:
    if db.shape != b.shape: 
        return "Ocurrió un problema con las dimensiones de las matrices"

    #Se crea una lista con los valores del diccionario. 
    gradientes = [dx, dw, db]
    
    #Se crea el diccionario. 
    diccionario_gradientes = dict(zip(claves, gradientes))

    return diccionario_gradientes

#Se prueba el ejemplo.
resultado_1 = linear_backward([[0.1, 0.2],[0.3, 0.4]], [[1, 2], [3, 4]], [[0.5, 0.6], [0.7, 0.8]], [0.1, 0.2])

for clave, valor in resultado_1.items():
    print(f"{clave}:")
    print(valor)
    print()

dx:
[[0.17 0.23]
 [0.39 0.53]]

dw:
[[1.  1.4]
 [1.4 2. ]]

db:
[0.4 0.6]



# Ejercicio 14: inicialización de los pesos <br>

Implemente la función xavier_init(dimensión), que inicialice los pesos usando la inicialización uniforme Xavier/Glorot. El parámetro de la dimensión corresponde al tamaño de la matriz de pesos: una tupla de la forma (fan_in, fan_out), donde fan_in es el número de entradas a la capa y fan_out es el número de salidas de la capa. Retorne un arreglo de Numpy de tamaño (fan_in, fan_out), cuyos elementos sean pesos muestreados de la distribución uniforme Xavier. <br>

*Requerimientos* <br>

1. Calcule el límite: <br>
$$
\sqrt{\frac{6}{fan_{in}+fan_{out}}}
$$
2. Genere una muestra de la distribución uniforme: U(-límite, límite)
3. Retorne un arreglo de Numpy de las dimensiones especificadas, deben coincidir con las dimensiones del parámetro. <br>
4. Use np.random.uniform para muestrear a partir de la distribución uniforme. <br>
5. Maneje los casos límite: valores muy pequeños o valores muy grandes para fan_in y fan_out. <br>

### Explicación de la fundamentación matemática <br>

El método de inicialización de pesos de Xavier es utilizado en redes neuronales con el objetivo de resolver el problema de los gradientes que desaparecen o explotan, lo que puede dificultar el entrenamiento de redes neuronales profundas. Su objetivo consiste en mantener la varianza en los pasos forward y backward de una red neuronal. En la inicialización de Xavier, el factor clave es el número de entradas y salidas en las capas, y no tanto el método de aleatorización: se busca mantener la varianza dentro de límites que permitan un aprendizaje efectivo. <br>

Los pesos se inicializan extrayéndolos de una distribución uniforme aleatoria dentro de un rango específico que se determina mediante la fórmula:
$$
x = \sqrt{\frac{6}{n_{inputs}+n_{outputs}}}
$$
Es importante destacar que n_inputs representa el número de entradas a la capa de entrada, mientras que n_outputs representa el número de salidas de la capa de salida. De esta forma, para cada peso de la red neuronal, se extrae un valor aleatorio de una distribución uniforme en el intervalo [-x, x]; al restringir los pesos a un rango determinado por x, se garantiza que la varianza de los pesos iniciales esté controlada y sea adecuada para un entrenamiento eficaz. <br>

Por otro lado, la importancia de la inicialización de pesos se detalla a través de los siguientes tres aspectos: <br>

- *Los gradientes que desaparecen o explotan*: el problema de los gradientes que desaparecen se produce cuando los gradientes durante el entrenamiento se vuelven extremadamente pequeños, lo que provoca que la red aprenda muy lentamente o no aprenda en absoluto. Después, el problema del gradiente explosivo se produce cuando los gradientes se vuelven extremadamente grandes, lo que genera un entrenamiento inestable e ineficaz. La inicialización de pesos de Xavier resuelve este problema.  <br> <br>

- *El sobreajuste*: la inicialización de pesos ayuda indirectamente a evitar el sobreajuste: garantiza que la red neuronal comience el entrenamiento con pesos bien escalados, lo que previene ciertos problemas como el desvanecimiento de los gradientes y la saturación neuronal. <br> <br>

- *La saturación*: la saturación de las funciones de activación se refiere a una situación en la que la salida de una función de activación se aproxima extremadamente a su valor mínimo o a su valor máximo para un amplio rango de entradas. La inicialización de pesos ayuda a mantener las activaciones en un rango equilibrado, evitando la saturación y los problemas asociados a los gradientes. 

**Información tomada de:** https://www.geeksforgeeks.org/deep-learning/xavier-initialization/

In [9]:
#Se importa Numpy 
import numpy as np

#Se crea la función:
def xavier_init(dimension):
    #Se desempaquetan los valores de la tupla del parámetro.
    fan_in, fan_out = dimension

    #Se calcula el límite superior
    limite_superior = np.sqrt(6/(fan_in + fan_out))

    #Se calcula el límite inferior
    limite_inferior = -limite_superior

    #Se usa np.random.uniform para muestrear: 
    pesos = np.random.uniform(limite_inferior, limite_superior, dimension)

    return pesos 

#Se prueba el ejemplo:
print(xavier_init((100, 50)))

[[-0.02592419 -0.02756816  0.15492561 ...  0.14237864 -0.03592398
   0.01291576]
 [ 0.01967171 -0.1096332   0.04273314 ...  0.02649997 -0.03627057
  -0.05800519]
 [-0.13618146  0.06180355 -0.14704622 ... -0.10813369 -0.13149009
   0.07740274]
 ...
 [-0.0842602  -0.11407851  0.13688355 ... -0.19099123 -0.19661444
   0.05912137]
 [ 0.08776477 -0.07416845  0.10298545 ...  0.19573583 -0.05441384
   0.07361774]
 [-0.06545253  0.00430415 -0.18132035 ...  0.11829099  0.08003839
  -0.06358727]]


# Ejercicio 18: normalización de lotes hacia adelante <br>

Implemente la función batchnorm_forward(x, gamma, beta, eps=1e-5, momentum=0.9, running_mean=None, running_var=None, train=True), que realice la normalización de los lotes. Debe retornar una tupla de la forma: (out, cache, new_running_mean, new_running_var). <br>

**Entradas** <br>
- *x*: el tensor de entrada, de dimensiones (N,D). <br>
- *gamma*: el parámetro de escala, de dimensiones (D,). <br>
- *beta*: el parámetro de desplazamiento, de tamaño (D,). <br>
- *eps*: una pequeña constante orientada a brindar estabilidad numérica. <br>
- *momentum*: el momentum para estadísticas de ejecución. <br>
- *running_mean*: la media cambiante de tamaño (D,). <br>
- *running_var*: la varianza cambiante de tamaño (D,). <br>
- *train*: un booleano que posee un valor verdadero si está en entrenamiento o que posee un valor falso si está en evaluación. <br>

**Salidas** <br>
- *out*: la salida normalizada, de dimensiones (N,D). <br> 
- *cache*: un diccionario que contiene los valores requeridos para el backward pass. Debe incluir: x, x_norm, mean, var, gamma, eps.  <br>
- *new_running_mean*: media cambiante actualizada, para la próxima iteración. <br>
- *new_running_var*: varianza cambiante actualizada, para la próxima iteración. <br>

*Requerimientos*

1. Maneje el modo de entrenamiento y el modo de evaluación correctamente. <br>
2. Calcule las estadísticas a lo largo de la dimensión de los lotes (axis = 0). <br>
3. Utilice broadcasting para la sustracción de la media y la varianza. <br>
4. Actualice las estadísticas cambiantes durante el entrenamiento. <br>
5. Almacene todos los valores necesarios para el backward pass. <br>
6. Maneje la inicialización de las estadísticas cambiantes (None → ceros). <br>
7. Use operaciones vectorizadas, evitar los ciclos explícitos. <br>

### Explicación de la fundamentación matemática <br>



In [7]:
#Se importa Numpy
import numpy as np 

#Se crea la función: 
def batchnorm_forward(x, gamma, beta, eps=1e-5, momentum=0.9, running_mean=None, running_var=None, train=True):

    filas, columnas = x.shape

    #Primero se inicializan las estadísticas cambiantes: 
    if running_mean is None: 
        #Dado que las estadísticas cambiantes se calculan a lo largo de las columnas. 
        running_mean = np.zeros(columnas)

    if running_var is None:
        #Dado que las estadísticas cambiantes se calculan a lo largo de las columnas.
        running_var = np.zeros(columnas)
    
    #Se maneja la fase de entrenamiento:
    if train: 
        #Se calcula la media del lote:
        media_lote = np.mean(x, axis= 0)

        #Se calcula la varianza del lote:
        varianza_lote = np.var(x, axis= 0)

        #Se normaliza: 
        x_normalizado = (x - media_lote) / np.sqrt(varianza_lote + eps)

        #Se escala y desplaza: 
        x_escalado_desplazado = gamma * x_normalizado + beta

        #Se actualizan las estadísticas cambiantes: 
        running_mean_nueva = (momentum * running_mean + (1 - momentum) * media_lote)
        running_var_nueva = (momentum * running_var + (1 - momentum) * varianza_lote)

        #Se almacenan los datos para el backward pass: 
        almacenado = {
            "x": x,
            "x_normalizado": x_normalizado,
            "media_lote": media_lote,
            "varianza_lote": varianza_lote,
            "gamma": gamma,
            "eps": eps
        }

    #Se maneja la fase de evaluación: 
    else:
        #Se utilizan las estadísticas para normalizar: 
        x_normalizado = (x - running_mean) / np.sqrt(running_var + eps)

        #Se escala y desplaza: 
        x_escalado_desplazado = gamma * x_normalizado + beta 

        #Se definen las variables en concordancia con las planteadas en el entrenamiento:
        running_mean_nueva = running_mean
        running_var_nueva = running_var

        almacenado = {
            "x": x,
            "x_normalizado": x_normalizado,
            "media_lote": running_mean,
            "varianza_lote": running_var,
            "gamma": gamma,
            "eps": eps
        }
    
    #Se retorna lo solicitado
    return x_normalizado, almacenado, running_mean_nueva, running_var_nueva

#Se prueba el ejemplo.
#Se definen las variables:
x = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
gamma = np.array([1.0, 1.0])
beta = np.array([0.0, 0.0])

#Se desempaqueta la tupla para imprimirlo ordenadamente y comparar los resultados:
salida, cache, running_mean, running_var = batchnorm_forward(x, gamma, beta, train=True)

#Se imprimen los resultados:
print("Salida:")
print(salida)

print("\nRunning mean:")
print(running_mean)

print("\nRunning var:")
print(running_var)


Salida:
[[-1.22474258 -1.22474258]
 [ 0.          0.        ]
 [ 1.22474258  1.22474258]]

Running mean:
[0.3 0.4]

Running var:
[0.26666667 0.26666667]
