# Ejercicio 1: Fundamentos del broadcasting en tensores <br>
Implementar una función broadcast_ops(X, b, w) que realice la operación Y = (X + b), donde X es una matriz de tamaño (N, D), b un vector de tamaño (D,) y w un vector de tamaño (N,). <br>

*Requerimientos* <br>
1- Retornar el tensor resultante Y de tamaño (N, D). <br>
2- Usar operaciones de la librería NumPy. <br>
3- No utilizar bucles for explícitos (hacer el código vectorizado). <br>

### Explicación de la fundamentación matemática <br>
En cuanto a principios matemáticos, esto no se trata de una multiplicación de matrices como en la teoría, si no que se utiliza la dimensión de los vectores b y w con el objetivo de multiplicar matrices elemento por elemento. <br>

Es importante mencionar otro principio matemático, y es que las dimensiones de las matrices y vectores deben coincidir. Por ejemplo, si X tiene dimensiones (N, D), entonces para sumar por cada elemento debemos hacer que el vector que se suma entrada por entrada sea de tamaño (D,). Además, se está utilizando el principio de broadcasting, que es un mecanismo de NumPy para aperar entre arreglos sin copiar los datos manualmente. <br>

### Explicación del código <br>
Para la solución, se reciben como parámetros una matriz X de tamaño (N, D) y dos vectores: b de tamaño (D, ) y w de tamaño (N, ). Dado que los datos pueden ingresarse inicialmente como listas de Python, primero se convierten a arreglos de NumPy mediante np.array(), para las operaciones vectorizadas. <br>

Una vez convertidos, el vector b tiene el tamaño adecuado para sumarse a cada columna de la matriz X. Utilizando el mecanismo de broadcasting de NumPy, esta suma se realiza directamente, ya que NumPy expande automáticamente el vector b a todas las filas de la matriz sin necesidad de replicarlo manualmente. <br>

Posteriormente, la forma original del vector w de tamnaño (N, ) no es compatible con una matriz de tamaño (N, D) para multiplicación elemento a elemento por filas. Por tanto, es necesario convertirlo a una forma (N, 1) utilizando reshape(-1,1). Finalmente, se realiza la operación (X + b) * w, obteniendo una nueva matriz de tamaño (N, D). <br>

In [ ]:
import numpy as np

def broadcast_ops(X, b, w):
    X = np.array(X)
    b = np.array(b)
    w = np.array(w)
    
    Y = (X + b) * w.reshape(-1,1)
    return Y

#Ejemplo y prueba sugerida provenientes de la página de PaperCode
X1 = [[1, 2], 
     [3, 4]]
print(broadcast_ops(X1, [10, 20], [0.5, 2]))


[[ 5.5 11. ]
 [26.  48. ]]


# Ejercicio 2: Multiplicación de matrices 
Dadas dos matrices A de tamaño (M, K) y B de tamaño (K, N), realice la operación del producto C = AB, de tamaño (M, N). <br>

En este caso, se piden dos funciones, una que utilice estructuras for y sin vectorizar, utilizando tres blucles for anidados, y posteriormente una versión vectorizada utilizando funciones de NumPy. <br>

*Requerimientos* <br>
1- Una función que calcule el producto de dos matrices utilizando tres bulcles for anidados. <br>
2- Otra función que utilice NumPy y optimice la operación anterior. Se pueden utilizar las operaciones "@" o np.dot de NumPy. <br>
3- Para la primera función, no usar las operaciones "@" o np.dot de NumPy. <br>
4- Para la segunda función, no usar bucles. <br>

### Explicación de la fundamentación matemática <br>
A diferencia del ejercicio anterior, aquí sí se trabaja con la multiplicación matricial que se conoce de la teoría, donde cada elemento de la matriz resultante se obtiene multiplicando una fila de la primera matriz por una columna de la segunda y sumando los productos correspondientes entrada por entrada. <br>

En cuanto a principios matemáticos, se utiliza la definición formal de multiplicación de matrices, igual como aparece en la página de PaperCode, donde el elemento ubicado en la posición (i,j) de la matriz resultado se calcula como la suma de los productos entre los elementos de la fila i de A y la columna j de B. Esto se expresa matemáticamente como: <br>

$$
C_{ij} = \sum_{k=0}^{K-1} A_{ik} B_{kj}
$$

Es importante mencionar que para que esta operación sea posible, las dimensiones internas deben coincidir. Es decir, si A tiene tamaño (M,K), entonces B debe tener tamaño (K,N). Esto garantiza que cada fila de la primera matriz tenga la misma cantidad de elementos que cada columna de la segunda matriz, y se devuelve una matriz de tamaño (M, N). <br>

### Explicación del código <br>
Para la solución, se utilizó el "esqueleto" del código que se encuentra en el ejercicio 2 de el módulo de PaperCode, así, se reciben como parámetros dos matrices A y B, que pueden ingresarse inicialmente como arreglos de NumPy de dos dimensiones. Primero se obtienen sus dimensiones mediante .shape, identificando el número de filas y columnas de cada una, y verificando que las dimensiones internas sean compatibles previo a realizar la operación. <br>

En la versión manual (matmul_naive), se inicializa una matriz de ceros de tamaño (M,N) para almacenar el resultado. Luego se utilizan tres ciclos anidados: el primero recorre las filas de A, el segundo las columnas de B, y el tercero realiza la suma acumulada de los productos correspondientes entre fila y columna para construir cada entrada de la matriz resultado. <br>

Posteriormente, en la versión vectorizada (matmul_vectorized), se utiliza la operación optimizada de NumPy mediante np.dot(), que lleva a cabo el producto matricial.<br>

In [ ]:
import numpy as np

#A pesar de que en esta versión no se van a utilizar las funciones de NumPy vectorizadas, si se utiliza la función shape que devuelve el tamaño de la matriz, es por esto que primero en ambos casos es necesario convertir las matrices a obejtos procesables por NumPy como los arreglos. 

def matmul_naive(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    A = np.array(A)
    B = np.array(B)

    M, K = A.shape
    K2, N = B.shape
    assert K == K2 #Verifica que sea verdadero, para ejecutar la multiplicación

    C = np.zeros((M, N))

    for i in range(M):
        for j in range(N):
            for k in range(K):
                C[i,j] += A[i,k] * B[k,j]
    return C

#Función vectorizada
def matmul_vectorized(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    A = np.array(A)
    B = np.array(B)
    return np.dot(A,B)


# Prueba sugerida por la página de PaperCode usando ambas funciones
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

print(matmul_naive(A, B))
print(matmul_vectorized(A, B))

[[19. 22.]
 [43. 50.]]
[[19 22]
 [43 50]]


# Ejercicio 3: nombre del ejercicio 
Agregar instrucciones del ejercicio 3

In [ ]:
# Este es el bloque de codigo del ejercicio 3.

# Ejercicio 4: nombre del ejercicio 
Agregar instrucciones del ejercicio 4

In [ ]:
# Este es el bloque de codigo del ejercicio 4.

# Ejercicio 5: nombre del ejercicio 
Agregar instrucciones del ejercicio 5

In [ ]:
# Este es el bloque de codigo del ejercicio 5.

# Ejercicio 6: nombre del ejercicio 
Agregar instrucciones del ejercicio 6

In [ ]:
# Este es el bloque de codigo del ejercicio 6. 

# Ejercicio 7: producto punto y producto cruz <br>
Implemente una función denominada producto_vectores(a,b), donde a y b son matrices (N,3), que representan lotes de vectores tridimensionales. Retorne un diccionario con el producto punto y el producto cruz de los parámetros. <br>

*Requerimientos* <br>
1- Calcule los productos de manera independiente para cada par de vectores en el lote. <br>
2- Use las operaciones vectorizadas de Numpy. <br>
3- Para el producto punto: use np.sum con un parámetro axis o np.einsum. <br>
4- Para el producto cruz: implemente la fórmula componente por componente usando operaciones vectorizadas. <br>
5- Maneje los lotes eficientemente, evite los bucles explícitos. <br>

### Explicación de la fundamentación matemática <br>
Intuitivamente, el producto punto brinda una idea sobre qué tanto apuntan dos vectores en la misma dirección y para cada par de vectores tridimensionales se calcula con la siguiente fórmula: 
$$
a ⋅ b = \sum_{i=1}^{3} a_{i} b_{i} = a_{x}b_{x} + a_{y}b_{y} + a_{z}b_{z}
$$
En palabras simples, se multiplican las entradas situadas en las mismas posiciones y se suma el resultado de estas multiplicaciones, de manera que se retorna un escalar. Es importante destacar que, con el objetivo de que el producto punto esté definido, es necesario que ambos vectores posean la misma dimensión.  <br>
Por otro lado, el producto cruz de dos vectores tridimensionales se calcula haciendo uso de la fórmula: 
$$
a × b = (a_{y}b_{z} - a_{z}b_{y},  a_{z}b_{x} - a_{x}b_{z},  a_{x}b_{y} - a_{y}b_{x})
$$
Es preciso señalar que el producto cruz está definido solo para vectores de tres dimensiones. El resultado corresponde a un vector tridimensional, que además es perpendicular a los vectores sobre los cuales se aplicó la fórmula. <br>

### Explicación del código <br>
En primera instancia, se convierten las matrices del parámetro a un arreglo de Numpy, con el objetivo de efectuar óptimamente las operaciones vectorizadas. Después, se procede a calcular el producto punto siguiendo las indicaciones de los requerimientos: se emplea np.sum con el parámetro axis=1, el cual indica que se debe sumar sobre las filas del arreglo; note que el arreglo sobre el cual se está sumando corresponde a la multiplicación de a y b, en vista de que anteriormente se definieron como arreglos de Numpy, dicha multiplicación actúa sobre las entradas en las mismas posiciones de los vectores y retorna un arreglo con el resultado. <br>
Por otra parte, para calcular el producto cruz componente por componente, se acude al slicing siguiendo la fórmula planteada. Cada componente se calcula por separado y representa un arreglo. Finalmente, los tres arreglos se unifican en un único arreglo de Numpy, organizándose como columnas. 


In [3]:
import numpy as np

def producto_vectores (a,b):
    #Se convierten las matrices en arreglos de Numpy para efectuar las operaciones vectorizadas. 
    a = np.asarray(a)
    b = np.asarray(b)
    #Se calcula el producto punto usando np.sum, con parametro axis=1 para que se sumen las filas. 
    producto_punto = np.sum(a * b, axis=1)
    #Se calcula el producto cruz, componente por componente, de manera vectorizada.
    componente_x = a[:, 1] * b[:, 2] - a[:, 2] * b[:, 1] #ay*bz - az*by
    componente_y = a[:, 2] * b[:, 0] - a[:, 0] * b[:, 2] #az*bx - ax*bz
    componente_z = a[:, 0] * b[:, 1] - a[:, 1] * b[:, 0] #ax*by - ay*bx
    #Se agrupan los vectores en un array de Numpy, donde cada vector representa una columna. 
    producto_cruz = np.column_stack((componente_x, componente_y, componente_z))

    return {"Producto punto": producto_punto, "Producto cruz": producto_cruz}

#Se prueba el ejemplo.
print(producto_vectores([[1, 0, 0]], [[0, 1, 0]]))

{'Producto punto': array([0]), 'Producto cruz': array([[0, 0, 1]])}


# Ejercicio 8: Fundamentos de la sumatoria de Einstein (einsum)
Implementar la función "einsum_ops(A, B)" donde A es una matriz de tamaño (N, D) y B es una matriz de tamaño (D, M). Retornar un diccionario con cinco operaciones fundamentales, totas implementando "np.einsum". Las operaciones se detallan a continuación: <br>

1- **transpose**: transponer A de tamaño (N, D) a (D, N). <br>
2- **sum**: sumar todos los elementos de A (resultado escalar). <br>
3- **row_sum**: suma de A sobre las filas (reducir columnas), el resultado debe ser un vector de tamaño (N, ). <br>
4- **col_sum**: suma de A sobre las columnas (reducir filas), el resultado es un vector de tamaño (D, ). <br>
5- **mat_mul**: producto matricial AB de tamaño (N, M). <br>

*Requerimientos* <br>
1- Usar "np.einsum" para todas las operaciones (no utilizar las funciones equivalentes de NumPy). <br>
2- Entender la notación de los índices y como funciona la sumatoria. <br>
3- Manejar el tamaño correcto de matrices y vectores para cada operación. <br>
4- Retornar los resultados en el formato de diccionario especificado. <br>

### Explicación de la fundamentación matemática

En este ejercicio se trabaja con la notación de suma de Einstein, que es una forma compacta de representar operaciones matriciales y de tensores mediante índices. La idea principal es que cada índice representa una dimensión de la matriz, y cuando un índice aparece repetido en una expresión, se interpreta automáticamente como una suma sobre esa dimensión. <br>

En las operaciones de suma y transposición, la notación permite indicar directamente qué índices se conservan y cuáles se eliminan. Por ejemplo, en la transposición de una matriz A, la expresión "ij->ji" indica que el índice de fila i y el de columna j intercambian su posición, generando una nueva matriz donde filas y columnas se invierten. Para la suma total "ij->", ambos índices desaparecen, lo que implica que todos los elementos de la matriz se suman en un único valor escalar. <br>

Para las sumas parciales, la lógica es similar: en "ij->i" se conserva únicamente el índice de fila, por lo que se suman todos los elementos de cada fila sobre las columnas; mientras que en "ij->j" se conserva el índice de columna, sumando sobre las filas. Matemáticamente, en notación de sumatoria, esto corresponde a: <br>

$$
R_i = \sum_{j} A_{ij}
$$

$$
C_j = \sum_{i} A_{ij}
$$	​

En el caso del producto matricial, se utiliza la notación "ik,kj->ij", donde el índice k aparece repetido en ambas matrices y por lo tanto se suma automáticamente. Esto corresponde exactamente a la definición formal de multiplicación de matrices, donde cada elemento de la matriz resultado se obtiene multiplicando una fila de la primera matriz por una columna de la segunda y sumando los productos correspondientes: <br>

$$
C_{ij} = \sum_{k=0}^{D-1} A_{ik} B_{kj}
$$

Es importante mencionar que para que esta operación sea posible, las dimensiones internas deben coincidir. Es decir, si A tiene tamaño (N,D), entonces B debe tener tamaño (D,M). Esto garantiza que la dimensión compartida D pueda contraerse correctamente, obteniéndose una matriz resultado de tamaño (N,M). <br>

### Explicación del código <br>

Para la solución, se define una función einsum_ops(A, B) que recibe como parámetros dos matrices A y B, ingresadas directamente como arreglos bidimensionales de NumPy. La matriz A tiene dimensión (N,D) y la matriz B dimensión (D,M), de manera que ambas sean compatibles para realizar el producto matricial en la última operación del diccionario. <br>

Dentro de la función, cada operación se implementa utilizando np.einsum(), que funciona como se explicó en la teoría anterior. Primero, para la transpuesta de A, se utiliza "ij->ji", donde se intercambian los índices de filas y columnas, obteniendo una matriz de dimensión (D,N). Luego, para calcular la suma total de los elementos de A, se emplea "ij->", indicando que todos los índices desaparecen y por tanto todos los valores se suman en un único escalar. <br>

Posteriormente, para obtener la suma por filas se utiliza "ij->i", conservando únicamente el índice de fila y sumando sobre las columnas, mientras que para la suma por columnas se utiliza "ij->j", conservando el índice de columna y sumando sobre las filas. Estas operaciones generan vectores unidimensionales con las sumas correspondientes. <br>

Finalmente, para el producto matricial entre A y B, se utiliza "ik,kj->ij", donde el índice k representa la dimensión compartida entre ambas matrices y es el que se contrae automáticamente en la suma. De esta forma se obtiene una matriz resultado de dimensión (N,M), equivalente al producto matricial convencional realizado con np.dot().

Al igual que en los ejercicios anteriores, se utiliza el "esqueleto" mostrado en la página de PaperCode, con el objetivo de seguir su misma estructura.

In [ ]:
import numpy as np
from typing import Dict, Union

#Como indica el enunciado se utilizan únicamente las operaciones de np.einsum
def einsum_ops(A: np.ndarray, B: np.ndarray) -> Dict[str, Union[np.ndarray, float]]:
    transpose = np.einsum("ij->ji", A)
    total_sum = np.einsum("ij->", A)
    row_sum = np.einsum("ij->i", A)
    col_sum = np.einsum("ij->j", A)
    matmul = np.einsum("ik,kj->ij", A, B)

    dict_res = {
        "transpose": transpose,
        "sum": total_sum,
        "row_sum": row_sum,
        "col_sum": col_sum,
        "matmul": matmul
    }

    return dict_res

# Prueba sugerida por la página de PaperCode

A = [[1, 2],    
     [3, 4]]
B = [[5, 6],     
     [7, 8]]

suma_ein = einsum_ops(A, B)

for key, valor in suma_ein.items():
    print(key)
    print(valor)
    print()


transpose
[[1 3]
 [2 4]]

sum
10

row_sum
[3 7]

col_sum
[4 6]

matmul
[[19 22]
 [43 50]]



# Ejercicio 9: nombre del ejercicio 
Agregar instrucciones del ejercicio 9

In [ ]:
# Este es el bloque de codigo del ejercicio 9. 

# Ejercicio 10: gradiente de suma <br>
Implemente la función grad_sum(grad_y, x_forma), la cual: tome grad_y, un escalar que representa ∂L/∂y; luego tome x_forma, una tupla que representa la forma original de la entrada x y finalmente retorne un tensor de gradiente de la forma x_forma, donde cada elemento iguale a grad_y. <br>

*Requerimientos* <br>
1- Retorne un tensor de la forma x_shape, relleno con grad_y. <br>
2- Use las operaciones de Numpy, por ejemplo, np.full o np.ones * grad_y. <br>
3- Maneje cualquier forma, no solo vectores de una dimensión. <br>
4- Asegúrese de que el tipo de dato de la salida sea igual al tipo de dato de grad_y. <br>

### Explicación de la fundamentación matemática




​

​

​
 

In [ ]:
# Este es el bloque de codigo del ejercicio 10. 

# Ejercicio 11: nombre del ejercicio 
Agregar instrucciones del ejercicio 11

In [ ]:
# Este es el bloque de codigo del ejercicio 11. 

# Ejercicio 12: nombre del ejercicio 
Agregar instrucciones del ejercicio 12

In [ ]:
# Este es el bloque de codigo del ejercicio 12. 

# Ejercicio 13: implementación de softmax <br>

Implemente una función softmax(x), que convierta logits en probabilidades. <br>
La entrada x corresponde a una matriz de la forma (N,C), donde N es el tamaño del lote (el número de muestras) y C es el número de clases; cada fila contiene logits (puntuaciones brutas) para una muestra. La salida debe ser una matriz de la forma (N,C), donde cada fila representa una distribución de probabilidad válida: todos los valores son mayores o iguales a cero, cada fila suma uno y logits más altos corresponden a probabilidades más altas. <br>
En cuanto al cálculo, se debe calcular el softmax de manera independiente para cada fila. Además, para cada muestra convierta sus C logits en C probabilidades. <br>

*Requerimientos* <br>
1- Implemente la versión numéricamente estable (restar el máximo antes de exponenciar). <br>
2- Calcule el softmax de manera independiente para cada fila. <br>
3- Retorne probabilidades de la forma (N,C), donde cada fila suma 1. <br>
4- Maneje casos límite: todos los ceros, los valores muy grandes y los valores muy pequeños. <br>
5- Use las operaciones de Numpy para cálculos vectorizados. <br>

### Explicación de la fundamentación matemática <br>



In [ ]:
# Este es el bloque de codigo del ejercicio 13. 

# Ejercicio 14: nombre del ejercicio 
Agregar instrucciones del ejercicio 14

In [ ]:
# Este es el bloque de codigo del ejercicio 14. 

# Ejercicio 15: nombre del ejercicio 
Agregar instrucciones del ejercicio 15

In [ ]:
# Este es el bloque de codigo del ejercicio 15. 