# Portada <br> 
Universidad de Costa Rica<br>
Departamento de Ciencias Actuariales<br><br>


Herramientas para Ciencia de Datos II<br><br>

<b>Bitácora 1</b><br>
Prof. Joshua Cervantes Artavia<br><br>

*Estudiantes*<br> 
Alexandra González Bermúdez, C4F535<br>
Daniela Prado Vargas,  <br>
Emily Estefanía Mora Contreras,  <br>
Liz de María Salazar Amaya, C4J618 <br>
Ericka <br> <br>


I Semestre <br>
2026

# Ejercicio 1: Fundamentos del broadcasting en tensores <br>
Implementar una función broadcast_ops(X, b, w) que realice la operación Y = (X + b), donde X es una matriz de tamaño (N, D), b un vector de tamaño (D,) y w un vector de tamaño (N,). <br>

*Requerimientos* <br>
1- Retornar el tensor resultante Y de tamaño (N, D). <br>
2- Usar operaciones de la librería NumPy. <br>
3- No utilizar bucles for explícitos (hacer el código vectorizado). <br>

### Explicación de la fundamentación matemática <br>
En cuanto a principios matemáticos, esto no se trata de una multiplicación de matrices como en la teoría, si no que se utiliza la dimensión de los vectores b y w con el objetivo de multiplicar matrices elemento por elemento. <br>

Es importante mencionar otro principio matemático, y es que las dimensiones de las matrices y vectores deben coincidir. Por ejemplo, si X tiene dimensiones (N, D), entonces para sumar por cada elemento debemos hacer que el vector que se suma entrada por entrada sea de tamaño (D,). Además, se está utilizando el principio de broadcasting, que es un mecanismo de NumPy para aperar entre arreglos sin copiar los datos manualmente. <br>

### Explicación del código <br>
Para la solución, se reciben como parámetros una matriz X de tamaño (N, D) y dos vectores: b de tamaño (D, ) y w de tamaño (N, ). Dado que los datos pueden ingresarse inicialmente como listas de Python, primero se convierten a arreglos de NumPy mediante np.array(), para las operaciones vectorizadas. <br>

Una vez convertidos, el vector b tiene el tamaño adecuado para sumarse a cada columna de la matriz X. Utilizando el mecanismo de broadcasting de NumPy, esta suma se realiza directamente, ya que NumPy expande automáticamente el vector b a todas las filas de la matriz sin necesidad de replicarlo manualmente. <br>

Posteriormente, la forma original del vector w de tamnaño (N, ) no es compatible con una matriz de tamaño (N, D) para multiplicación elemento a elemento por filas. Por tanto, es necesario convertirlo a una forma (N, 1) utilizando reshape(-1,1). Finalmente, se realiza la operación (X + b) * w, obteniendo una nueva matriz de tamaño (N, D). <br>

In [ ]:
import numpy as np

def broadcast_ops(X, b, w):
    X = np.array(X)
    b = np.array(b)
    w = np.array(w)
    
    Y = (X + b) * w.reshape(-1,1)
    return Y

#Ejemplo y prueba sugerida provenientes de la página de PaperCode
X1 = [[1, 2], 
     [3, 4]]
print(broadcast_ops(X1, [10, 20], [0.5, 2]))


[[ 5.5 11. ]
 [26.  48. ]]


# Ejercicio 2: Multiplicación de matrices 
Dadas dos matrices A de tamaño (M, K) y B de tamaño (K, N), realice la operación del producto C = AB, de tamaño (M, N). <br>

En este caso, se piden dos funciones, una que utilice estructuras for y sin vectorizar, utilizando tres blucles for anidados, y posteriormente una versión vectorizada utilizando funciones de NumPy. <br>

*Requerimientos* <br>
1- Una función que calcule el producto de dos matrices utilizando tres bulcles for anidados. <br>
2- Otra función que utilice NumPy y optimice la operación anterior. Se pueden utilizar las operaciones "@" o np.dot de NumPy. <br>
3- Para la primera función, no usar las operaciones "@" o np.dot de NumPy. <br>
4- Para la segunda función, no usar bucles. <br>

### Explicación de la fundamentación matemática <br>
A diferencia del ejercicio anterior, aquí sí se trabaja con la multiplicación matricial que se conoce de la teoría, donde cada elemento de la matriz resultante se obtiene multiplicando una fila de la primera matriz por una columna de la segunda y sumando los productos correspondientes entrada por entrada. <br>

En cuanto a principios matemáticos, se utiliza la definición formal de multiplicación de matrices, igual como aparece en la página de PaperCode, donde el elemento ubicado en la posición (i,j) de la matriz resultado se calcula como la suma de los productos entre los elementos de la fila i de A y la columna j de B. Esto se expresa matemáticamente como: <br>

$$
C_{ij} = \sum_{k=0}^{K-1} A_{ik} B_{kj}
$$

Es importante mencionar que para que esta operación sea posible, las dimensiones internas deben coincidir. Es decir, si A tiene tamaño (M,K), entonces B debe tener tamaño (K,N). Esto garantiza que cada fila de la primera matriz tenga la misma cantidad de elementos que cada columna de la segunda matriz, y se devuelve una matriz de tamaño (M, N). <br>

### Explicación del código <br>
Para la solución, se utilizó el "esqueleto" del código que se encuentra en el ejercicio 2 de el módulo de PaperCode, así, se reciben como parámetros dos matrices A y B, que pueden ingresarse inicialmente como arreglos de NumPy de dos dimensiones. Primero se obtienen sus dimensiones mediante .shape, identificando el número de filas y columnas de cada una, y verificando que las dimensiones internas sean compatibles previo a realizar la operación. <br>

En la versión manual (matmul_naive), se inicializa una matriz de ceros de tamaño (M,N) para almacenar el resultado. Luego se utilizan tres ciclos anidados: el primero recorre las filas de A, el segundo las columnas de B, y el tercero realiza la suma acumulada de los productos correspondientes entre fila y columna para construir cada entrada de la matriz resultado. <br>

Posteriormente, en la versión vectorizada (matmul_vectorized), se utiliza la operación optimizada de NumPy mediante np.dot(), que lleva a cabo el producto matricial.<br>

In [ ]:
import numpy as np

#A pesar de que en esta versión no se van a utilizar las funciones de NumPy vectorizadas, si se utiliza la función shape que devuelve el tamaño de la matriz, es por esto que primero en ambos casos es necesario convertir las matrices a obejtos procesables por NumPy como los arreglos. 

def matmul_naive(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    A = np.array(A)
    B = np.array(B)

    M, K = A.shape
    K2, N = B.shape
    assert K == K2 #Verifica que sea verdadero, para ejecutar la multiplicación

    C = np.zeros((M, N))

    for i in range(M):
        for j in range(N):
            for k in range(K):
                C[i,j] += A[i,k] * B[k,j]
    return C

#Función vectorizada
def matmul_vectorized(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    A = np.array(A)
    B = np.array(B)
    return np.dot(A,B)


# Prueba sugerida por la página de PaperCode usando ambas funciones
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

print(matmul_naive(A, B))
print(matmul_vectorized(A, B))

[[19. 22.]
 [43. 50.]]
[[19 22]
 [43 50]]


# Ejercicio 3: Operaciones elemento a elemento 
Implementar una función elementwise_ops(a, b)que tome dos tensores 'a' de 'b' de la misma forma y devuelva un diccionario que contenga tres operaciones fundamentales elemento a elemento:a
1. "add": Adición elemento por elemento a elemento 
2. "mul": Multiplicación elemento a elemento (producto de Hadamard)
3. "div": División segura por elementos

## Explicación de la fundamentación matemática
Al igual que el ejercicio 1, la operación de multiplicación se aplica elemento por elemento sin tomar en cuenta el principio de producto vectorial. En el caso de la división, para evitar problemas al dividir entre 0, se añade una variable llamada epsilon para añadir una cantidad relativamente muy pequeña al valor que tome el denominador, de esta forma lograr que la operación no se indefina y a la vez obtener un resultado cercano al valor exacto.

## Explicación del código
Primero, se convierte los tensores a y b a tipo ndarray para que Numpy pueda manipularlos de manera directa. Además, se define la variable epsilon igual a 1e-8 que es un número relativamente pequeño para evitar problemas al dividir por cero.

En cada key del diccionario, se añaden las operaciones, el primer key se llama "suma" donde se utiliza a + b, el segundo key se llama mul donde se utiliza a * b donde Numpy multiplica elemento por elemento y el tercer key se llama div donde se realiza la operación a / (b + epsilon). 

En las indicaciones se solicita que los tensores tengan la misma forma, por lo tanto, para añadir los resultados de las operación al diccionario que esperamos devolver, se verifica si está condición se cumple. Si no se cumple, se devuelve un mensaje indicando el error. 

In [4]:

import numpy as np

def elementwise_ops(a, b):
    a = np.array(a)
    b = np.array(b)
    epsilon = 1e-8 # Para evitar dividir por cero
    if a.shape == b.shape: #Verficamos si el tamaño coincide
        dicc = {"add": a + b, "mul": a * b , "div": a / (b + epsilon)}
        return dicc
    else: 
        return "No se puede aplicar las operaciones, el tamaño no coincide."
    
    ## Ejemplo de PaperCode
a = [1.0, 2.0]
b = [0.0, 2.0]
print("Resultados: " , elementwise_ops(a, b))


Resultados:  {'add': array([1., 4.]), 'mul': array([0., 4.]), 'div': array([1.00000000e+08, 9.99999995e-01])}


# Ejercicio 4: nombre del ejercicio 
Agregar instrucciones del ejercicio 4

In [ ]:
# Este es el bloque de codigo del ejercicio 4.

# Ejercicio 5: nombre del ejercicio 
Agregar instrucciones del ejercicio 5

In [ ]:
# Este es el bloque de codigo del ejercicio 5.

# Ejercicio 6: nombre del ejercicio 
Agregar instrucciones del ejercicio 6

In [ ]:
# Este es el bloque de codigo del ejercicio 6. 

# Ejercicio 7: producto punto y producto cruz <br>
Implemente una función denominada producto_vectores(a,b), donde a y b son matrices (N,3), que representan lotes de vectores tridimensionales. Retorne un diccionario con el producto punto y el producto cruz de los parámetros. <br>

*Requerimientos* <br>
1- Calcule los productos de manera independiente para cada par de vectores en el lote. <br>
2- Use las operaciones vectorizadas de Numpy. <br>
3- Para el producto punto: use np.sum con un parámetro axis o np.einsum. <br>
4- Para el producto cruz: implemente la fórmula componente por componente usando operaciones vectorizadas. <br>
5- Maneje los lotes eficientemente, evite los bucles explícitos. <br>

### Explicación de la fundamentación matemática <br>
Intuitivamente, el producto punto brinda una idea sobre qué tanto apuntan dos vectores en la misma dirección y para cada par de vectores tridimensionales se calcula con la siguiente fórmula: 
$$
a ⋅ b = \sum_{i=1}^{3} a_{i} b_{i} = a_{x}b_{x} + a_{y}b_{y} + a_{z}b_{z}
$$
En palabras simples, se multiplican las entradas situadas en las mismas posiciones y se suma el resultado de estas multiplicaciones, de manera que se retorna un escalar. Es importante destacar que, con el objetivo de que el producto punto esté definido, es necesario que ambos vectores posean la misma dimensión.  <br>
Por otro lado, el producto cruz de dos vectores tridimensionales se calcula haciendo uso de la fórmula: 
$$
a × b = (a_{y}b_{z} - a_{z}b_{y},  a_{z}b_{x} - a_{x}b_{z},  a_{x}b_{y} - a_{y}b_{x})
$$
Es preciso señalar que el producto cruz está definido solo para vectores de tres dimensiones. El resultado corresponde a un vector tridimensional, que además es perpendicular a los vectores sobre los cuales se aplicó la fórmula. <br>

### Explicación del código <br>
En primera instancia, se convierten las matrices del parámetro a un arreglo de Numpy, con el objetivo de efectuar óptimamente las operaciones vectorizadas. Después, se procede a calcular el producto punto siguiendo las indicaciones de los requerimientos: se emplea np.sum con el parámetro axis=1, el cual indica que se debe sumar sobre las filas del arreglo; note que el arreglo sobre el cual se está sumando corresponde a la multiplicación de a y b, en vista de que anteriormente se definieron como arreglos de Numpy, dicha multiplicación actúa sobre las entradas en las mismas posiciones de los vectores y retorna un arreglo con el resultado. <br>
Por otra parte, para calcular el producto cruz componente por componente, se acude al slicing siguiendo la fórmula planteada. Cada componente se calcula por separado y representa un arreglo. Finalmente, los tres arreglos se unifican en un único arreglo de Numpy, organizándose como columnas. 


In [3]:
import numpy as np

def producto_vectores (a,b):
    #Se convierten las matrices en arreglos de Numpy para efectuar las operaciones vectorizadas. 
    a = np.asarray(a)
    b = np.asarray(b)
    #Se calcula el producto punto usando np.sum, con parametro axis=1 para que se sumen las filas. 
    producto_punto = np.sum(a * b, axis=1)
    #Se calcula el producto cruz, componente por componente, de manera vectorizada.
    componente_x = a[:, 1] * b[:, 2] - a[:, 2] * b[:, 1] #ay*bz - az*by
    componente_y = a[:, 2] * b[:, 0] - a[:, 0] * b[:, 2] #az*bx - ax*bz
    componente_z = a[:, 0] * b[:, 1] - a[:, 1] * b[:, 0] #ax*by - ay*bx
    #Se agrupan los vectores en un array de Numpy, donde cada vector representa una columna. 
    producto_cruz = np.column_stack((componente_x, componente_y, componente_z))

    return {"Producto punto": producto_punto, "Producto cruz": producto_cruz}

#Se prueba el ejemplo.
print(producto_vectores([[1, 0, 0]], [[0, 1, 0]]))

{'Producto punto': array([0]), 'Producto cruz': array([[0, 0, 1]])}


# Ejercicio 8: Fundamentos de la sumatoria de Einstein (einsum)
Implementar la función "einsum_ops(A, B)" donde A es una matriz de tamaño (N, D) y B es una matriz de tamaño (D, M). Retornar un diccionario con cinco operaciones fundamentales, totas implementando "np.einsum". Las operaciones se detallan a continuación: <br>

1- **transpose**: transponer A de tamaño (N, D) a (D, N). <br>
2- **sum**: sumar todos los elementos de A (resultado escalar). <br>
3- **row_sum**: suma de A sobre las filas (reducir columnas), el resultado debe ser un vector de tamaño (N, ). <br>
4- **col_sum**: suma de A sobre las columnas (reducir filas), el resultado es un vector de tamaño (D, ). <br>
5- **mat_mul**: producto matricial AB de tamaño (N, M). <br>

*Requerimientos* <br>
1- Usar "np.einsum" para todas las operaciones (no utilizar las funciones equivalentes de NumPy). <br>
2- Entender la notación de los índices y como funciona la sumatoria. <br>
3- Manejar el tamaño correcto de matrices y vectores para cada operación. <br>
4- Retornar los resultados en el formato de diccionario especificado. <br>

### Explicación de la fundamentación matemática

En este ejercicio se trabaja con la notación de suma de Einstein, que es una forma compacta de representar operaciones matriciales y de tensores mediante índices. La idea principal es que cada índice representa una dimensión de la matriz, y cuando un índice aparece repetido en una expresión, se interpreta automáticamente como una suma sobre esa dimensión. <br>

En las operaciones de suma y transposición, la notación permite indicar directamente qué índices se conservan y cuáles se eliminan. Por ejemplo, en la transposición de una matriz A, la expresión "ij->ji" indica que el índice de fila i y el de columna j intercambian su posición, generando una nueva matriz donde filas y columnas se invierten. Para la suma total "ij->", ambos índices desaparecen, lo que implica que todos los elementos de la matriz se suman en un único valor escalar. <br>

Para las sumas parciales, la lógica es similar: en "ij->i" se conserva únicamente el índice de fila, por lo que se suman todos los elementos de cada fila sobre las columnas; mientras que en "ij->j" se conserva el índice de columna, sumando sobre las filas. Matemáticamente, en notación de sumatoria, esto corresponde a: <br>

$$
R_i = \sum_{j} A_{ij}
$$

$$
C_j = \sum_{i} A_{ij}
$$	​

En el caso del producto matricial, se utiliza la notación "ik,kj->ij", donde el índice k aparece repetido en ambas matrices y por lo tanto se suma automáticamente. Esto corresponde exactamente a la definición formal de multiplicación de matrices, donde cada elemento de la matriz resultado se obtiene multiplicando una fila de la primera matriz por una columna de la segunda y sumando los productos correspondientes: <br>

$$
C_{ij} = \sum_{k=0}^{D-1} A_{ik} B_{kj}
$$

Es importante mencionar que para que esta operación sea posible, las dimensiones internas deben coincidir. Es decir, si A tiene tamaño (N,D), entonces B debe tener tamaño (D,M). Esto garantiza que la dimensión compartida D pueda contraerse correctamente, obteniéndose una matriz resultado de tamaño (N,M). <br>

### Explicación del código <br>

Para la solución, se define una función einsum_ops(A, B) que recibe como parámetros dos matrices A y B, ingresadas directamente como arreglos bidimensionales de NumPy. La matriz A tiene dimensión (N,D) y la matriz B dimensión (D,M), de manera que ambas sean compatibles para realizar el producto matricial en la última operación del diccionario. <br>

Dentro de la función, cada operación se implementa utilizando np.einsum(), que funciona como se explicó en la teoría anterior. Primero, para la transpuesta de A, se utiliza "ij->ji", donde se intercambian los índices de filas y columnas, obteniendo una matriz de dimensión (D,N). Luego, para calcular la suma total de los elementos de A, se emplea "ij->", indicando que todos los índices desaparecen y por tanto todos los valores se suman en un único escalar. <br>

Posteriormente, para obtener la suma por filas se utiliza "ij->i", conservando únicamente el índice de fila y sumando sobre las columnas, mientras que para la suma por columnas se utiliza "ij->j", conservando el índice de columna y sumando sobre las filas. Estas operaciones generan vectores unidimensionales con las sumas correspondientes. <br>

Finalmente, para el producto matricial entre A y B, se utiliza "ik,kj->ij", donde el índice k representa la dimensión compartida entre ambas matrices y es el que se contrae automáticamente en la suma. De esta forma se obtiene una matriz resultado de dimensión (N,M), equivalente al producto matricial convencional realizado con np.dot().

Al igual que en los ejercicios anteriores, se utiliza el "esqueleto" mostrado en la página de PaperCode, con el objetivo de seguir su misma estructura.

In [ ]:
import numpy as np
from typing import Dict, Union

#Como indica el enunciado se utilizan únicamente las operaciones de np.einsum
def einsum_ops(A: np.ndarray, B: np.ndarray) -> Dict[str, Union[np.ndarray, float]]:
    transpose = np.einsum("ij->ji", A)
    total_sum = np.einsum("ij->", A)
    row_sum = np.einsum("ij->i", A)
    col_sum = np.einsum("ij->j", A)
    matmul = np.einsum("ik,kj->ij", A, B)

    dict_res = {
        "transpose": transpose,
        "sum": total_sum,
        "row_sum": row_sum,
        "col_sum": col_sum,
        "matmul": matmul
    }

    return dict_res

# Prueba sugerida por la página de PaperCode

A = [[1, 2],    
     [3, 4]]
B = [[5, 6],     
     [7, 8]]

suma_ein = einsum_ops(A, B)

for key, valor in suma_ein.items():
    print(key)
    print(valor)
    print()


transpose
[[1 3]
 [2 4]]

sum
10

row_sum
[3 7]

col_sum
[4 6]

matmul
[[19 22]
 [43 50]]



# Ejercicio 9: nombre del ejercicio 
Agregar instrucciones del ejercicio 9

In [ ]:
# Este es el bloque de codigo del ejercicio 9. 

# Ejercicio 10: gradiente de una suma <br>
Implemente la función grad_sum(grad_y, x_forma), la cual: tome grad_y, un escalar que representa ∂L/∂y; luego tome x_forma, una tupla que representa la forma original de la entrada x y finalmente retorne un tensor de gradiente de la forma x_forma, donde cada elemento iguale a grad_y. <br>

*Requerimientos* <br>
1- Retorne un tensor de la forma x_shape, relleno con grad_y. <br>
2- Use las operaciones de Numpy, por ejemplo, np.full o np.ones * grad_y. <br>
3- Maneje cualquier forma, no solo vectores de una dimensión. <br>
4- Asegúrese de que el tipo de dato de la salida sea igual al tipo de dato de grad_y. <br>

### Explicación de la fundamentación matemática
En primera instancia, se define la siguiente operación:
$$
y = sum(x) = \sum_{i=1}^{N} x_{i}
$$ 
De la operación anterior, se tiene que x representa un vector de tamaño (N, ), el cual contiene N elementos. Por otro lado, y es un escalar que representa el resultado de la suma de todos los elementos de x. <br>
Intuitivamente, se tiene que el gradiente corresponde a una tasa de cambio: la tasa de cambio de una función escalar respecto a variables determinadas, es decir, indica la dirección y la magnitud en la que cambia una función de acuerdo a ciertas variables. Así, al definir grad_y como ∂L/∂y donde L es la pérdida, se está midiendo qué tanto cambia la función de pérdida según y. <br> 
Note que se busca calcular ∂L/∂x, además recuerde que x es un vector formado por entradas xi; empleando la regla de la cadena y descomponiendo ∂L/∂x en cada ∂L/∂xi se tiene lo siguiente: 
$$
\frac{∂L}{∂x_{i}}  = \frac{∂L}{∂y} ⋅ \frac{∂y}{∂x_{i}}
$$
Se sabe que grad_y = ∂L/∂y, por lo que el enfoque recae sobre ∂y/∂xi. De nuevo, ∂y/∂xi representa qué tanto cambia la función y de acuerdo a xi. Dado que la función y está conformada por un único elemento xi (general), con el subíndice i que se encuentra entre 1 y N, derivando parcialmente se obtiene:
$$
\frac{∂y}{∂x_{i}}  = \frac{\sum_{j=1}^{N} x_{j}}{∂xi} = 1; 1 \leq i \leq N
$$
Finalmente: 
$$
\frac{∂L}{∂x_{i}}  = \frac{∂L}{∂y} ⋅ \frac{∂y}{∂x_{i}} = grad_y ⋅ 1 = grad_y
$$
​Dado que xi se tomó como un elemento general, visualice que el procedimiento detallado antes se repite para todos los elementos de x, de manera que ∂L/∂x corresponde a un vector del mismo tamaño de x, cuyas entradas son iguales al gradiente de la suma, grad_y. <br>
 
### Explicación del código <br>
Siguiendo las instrucciones detalladas en los requerimientos, se utiliza la operación de Numpy denominada np.full. Dicha operación se encarga de crear un arreglo de Numpy recibiendo los siguientes parámetros: np.full(tamaño, valor_rellenar, dtype = tipo_de_dato). El parámetro *tamaño* indica precisamente el tamaño del arreglo que se creará, después, *valor_rellenar* representa el valor constante con el que se rellenarán todas las posiciones del arreglo, finalmente, *tipo_de_dato* corresponde al tipo de dato con el que se rellenarán las posiciones. Note que, con el objetivo de cumplir con el requerimiento que establece que  el tipo de dato de la salida debe coincidir con el tipo de dato de grad_y, se emplea .dtype, un atributo de los arreglos de Numpy que describe el tipo de dato de los elementos que contiene el arreglo. Al convertir grad_y en un arreglo de Numpy y emplear sobre él .dtype, se obtiene el tipo de dato de grad_y. <br>
En vista de que el gradiente se "divide" equitativamente: si la suma contribuyó con g a la pérdida, entonces cada elemento que contribuyó a la suma recibe un gradiente de g, y además el parámetro x_forma representa el tamaño original de la entrada x, se debe retornar un arreglo de tamaño x_forma cuyas entradas sean iguales al gradiente de la suma, en este caso, grad_y. 

In [1]:
import numpy as np
def grad_sum(grad_y, x_forma): 
    return np.full(x_forma, grad_y, dtype = np.array(grad_y).dtype)

#Se prueba el ejemplo
print(grad_sum(0.5, (3,)))


[0.5 0.5 0.5]


# Ejercicio 11: nombre del ejercicio 
Agregar instrucciones del ejercicio 11

In [ ]:
# Este es el bloque de codigo del ejercicio 11. 

# Ejercicio 12: Codificación One-Hot
Implemente una función llamada one_hot_encode(indices, num_classes) que transforme un vector de etiquetas enteras en una representación de matriz binaria. La función debe identificar las categorías únicas, construir una matriz de dimensiones N×C (donde N es el número de muestras y C el número de clases) e insertar un 1.0 en la columna correspondiente al índice de cada muestra, manteniendo el resto de la fila en 0.0.<br>

*Requerimientos*<br>
1- Maneje casos borde: arreglos vacíos, una sola muestra, una sola clase.<br>
2- Asegúrese de que todos los índices sean válidos ($0 \le \text{índice} < C$).<br>
3- Devuelva un arreglo de tipo flotante (dtype=float32 o float64) para estabilidad numérica.<br>
4- Utilice operaciones vectorizadas (evite bucles explícitos).<br>

### Explicación de la fundamentación matemática

La idea principal de este método es convertir categorías en posiciones dentro de un espacio vectorial. El problema que resolvemos es que números como 0, 1 o 2, cuando representan clases, no tienen un significado de magnitud; o sea, que una clase sea “2” no significa que sea mayor que “0”, solo que es distinta. Para evitar que un modelo matemático interprete mal esto, cada categoría se transforma en un vector. Es decir, si hay C clases en total, cada dato se convierte en una fila de una matriz donde solo una posición tiene valor 1.0 y todas las demás posiciones tienen valor 0.0. En términos simples, se crea un espacio con tantas dimensiones como categorías haya, para cada dato se busca la posición que corresponde a su clase y en esa posición se coloca un 1.0, y en las demás 0.0. <br>

Matemáticamente, esto se puede expresar como una función indicadora, donde cada componente del vector está definido como:

$$
one\_hot[j,k] =
\begin{cases}
1 & k = i_j \\
0 & \text{en otro caso}
\end{cases}
$$ 

Esto significa que el valor es 1 únicamente cuando la posición coincide con la clase correcta, y 0 en cualquier otro caso. Esto es importante porque convierte cada etiqueta en una distribución de probabilidad perfecta. Es decir, al tener un “1” en la clase correcta y “0” en las demás, estamos diciendo que hay 100% de certeza de que el dato pertenece a esa categoría. <br>

### Explicación del código

Este código lo que hace es convertir una lista de clases en una matriz donde cada clase se representa como un vector. Primero, toma la lista de índices y la convierte en un arreglo de NumPy para poder trabajar de forma vectorizada. Luego, obtiene cuántos datos hay (N). Si la lista está vacía, devuelve directamente una matriz vacía con el número correcto de columnas (una por cada clase) para evitar errores. Después, verifica que todos los valores de indices estén dentro del rango válido, es decir, que no sean negativos ni mayores o iguales al número de clases, evitando así acceder a posiciones que no existen en la matriz.<br>
A continuación, crea una matriz llena de ceros de tamaño (N, C), donde N es la cantidad de datos y C es el número de clases; esa matriz es donde se construye la representación buscada. En lugar de usar ciclos, se utiliza indexación avanzada de NumPy: np.arange(N) indica las filas y indices señala en qué columna va el 1 en cada fila. Con esto, NumPy coloca un 1.0 en la posición correcta de cada fila y deja el resto en 0.0. Al final, devuelve la matriz resultante, donde cada fila representa un dato y tiene un 1 en la posición de su clase y 0 en todas las demás.<br>


In [7]:
import numpy as np

def one_hot_encode(indices: np.ndarray, num_classes: int) -> np.ndarray:
    
    # convertir a array de numpy
    indices = np.array(indices, dtype=np.int64)
    N = indices.shape[0]

    # caso de un array vacío
    if N == 0:
        return np.zeros((0, num_classes), dtype=np.float64)

    # si hay índices inválidos devuelve matriz de ceros
    if np.any(indices < 0) or np.any(indices >= num_classes):
        return np.zeros((N, num_classes), dtype=np.float64)

    # crear matriz de ceros
    result = np.zeros((N, num_classes), dtype=np.float64)

    # asignación con indexación avanzada utilizando sugerencia
    result[np.arange(N), indices] = 1.0

    return result

# Se prueba el ejemplo 
indices = [0, 2, 1]     
num_classes = 3          
print(one_hot_encode(indices, num_classes))

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


# Ejercicio 13: implementación de softmax <br>

Implemente una función softmax(x), que convierta logits en probabilidades. <br>
La entrada x corresponde a una matriz de la forma (N,C), donde N es el tamaño del lote (el número de muestras) y C es el número de clases; cada fila contiene logits (puntuaciones brutas) para una muestra. La salida debe ser una matriz de la forma (N,C), donde cada fila representa una distribución de probabilidad válida: todos los valores son mayores o iguales a cero, cada fila suma uno y logits más altos corresponden a probabilidades más altas. <br>
En cuanto al cálculo, se debe calcular el softmax de manera independiente para cada fila. Además, para cada muestra convierta sus C logits en C probabilidades. <br>

*Requerimientos* <br>
1- Implemente la versión numéricamente estable (restar el máximo antes de exponenciar). <br>
2- Calcule el softmax de manera independiente para cada fila. <br>
3- Retorne probabilidades de la forma (N,C), donde cada fila suma 1. <br>
4- Maneje casos límite: todos los ceros, los valores muy grandes y los valores muy pequeños. <br>
5- Use las operaciones de Numpy para cálculos vectorizados. <br>

### Explicación de la fundamentación matemática <br>
La función softmax es un componente matemático que se encarga de convertir un vector de números reales, cuyas entradas se denominan logits, en una distribución de probabilidad válida: los valores de las probabilidades se encuentran en [0,1] y las filas suman un total de 1. A continuación, se detalla la fórmula aplicada para calcular el softmax:
$$
softmax(x)_{i} = \frac{e^{x_{i} - max(x)}}{\sum_{j=1}^{C} e^{x_{j} - max(x)}}
$$
La resta situada en el exponente, de cada elemento respecto al máximo valor (logit) de la fila sobre la que se está trabajando, es un agregado a la fórmula cuyo objetivo consiste en evitar el desbordamiento numérico. Lo anterior es factible debido a la propiedad de la invarianza: agregar una constante a todos los logits no cambia las probabilidades. De esta forma, se asegura la estabilidad numérica. Asimismo, la exponenciación de euler hace que todos los valores sean positivos. <br>
Por otro lado, la constante de normalización se encarga de asegurar que las probabilidades de las filas sumen 1. <br>
Todo esto en conjunto, genera la construcción de una distribución de probabilidad válida. <br>

### Explicación del código <br>
En primera instancia, se convierte la matriz en un arreglo de Numpy con el objetivo de aplicar óptimamente las operaciones vectorizadas necesarias. Después, se calcula el valor máximo (logit) de cada fila y se calculan los exponentes de cada entrada. Para realizar la resta en los exponentes, es preciso actualizar la forma del vector de los valores máximos, de manera que sea un vector con una única columna, cuyas filas representan el valor máximo de cada fila de la matriz, así por ejemplo, cada entrada de la primera fila de la matriz se restará con el valor de la primera fila del vector de los valores máximos, el cual corresponde al máximo valor de la primera fila de la matriz; este proceso se repite con cada una de las filas. <br>
Seguidamente, se exponencian las entradas haciendo uso de la operación np.exp, la cual se encarga de exponenciar euler a los valores del parámetro, que en este caso corresponde a un arreglo de Numpy, por lo que se mantiene la estructura de la matriz. <br>
Luego, se procede a calcular las constantes de normalización de cada fila, que corresponden a la suma de los elementos exponenciados de la fila correspondiente. Por último, similar al caso de la resta, para efectuar la división vectorizada de las entradas de una fila con la constante de normalización asociada a dicha fila, se necesita que el vector de las constantes de normalización posea una única columna, por lo que se recurre a la función de .reshape(). 



In [3]:
import numpy as np
def softmax (x): 
    #Se convierte la matriz a un arreglo de Numpy para aplicar operaciones vectorizadas.
    x = np.asarray(x)
    #Se extraen los valores máximos de cada fila.
    max_filas = np.max(x, axis=1)
    #Se calculan los exponente de cada fila. Se convierte el vector max en un vector de una única columna. 
    exponentes = x - max_filas.reshape(-1,1)
    #Se calculan las exponenciales con la operacion np.exp.
    exponenciales = np.exp(exponentes)
    #Se suman las exponenciales por filas para obtener la constantes de normalizacion.
    constantes_normalizacion = np.sum(exponenciales, axis=1)
    #Se normaliza y se contruye el softmax. De nuevo, se convierte el vector de las constantes de normalizacion a un vector columna. 
    softmax = exponenciales / constantes_normalizacion.reshape(-1, 1)
    
    return softmax 

#Se prueba el ejemplo
print(softmax([[2.0, 1.0, 0.1], [0.5, 2.5, 0.3]]))

[[0.65900114 0.24243297 0.09856589]
 [0.10860373 0.80247906 0.08891721]]


# Ejercicio 14: Pérdida de Entropía Cruzada (Manual)
Implemente una función llamada cross_entropy_loss(probs, targets) que calcule el promedio de la pérdida de entropía cruzada para un lote de muestras. La función debe recibir una matriz de probabilidades de forma (N,C) y un vector de etiquetas reales, para luego extraer la probabilidad asignada a la clase correcta de cada muestra mediante indexación avanzada. Finalmente, debe calcular el logaritmo negativo de estas probabilidades, aplicando un factor de estabilidad numérica (ϵ=1e−9), y retornar el promedio escalar de estos valores para todo el lote.<br>

*Requerimientos*<br>
1- Utilice la indexación avanzada para seleccionar eficientemente las probabilidades correctas.<br>
2- Añada un épsilon (ϵ=1e−9) dentro del logaritmo para la estabilidad numérica.<br>
3- Devuelva un escalar (pérdida promedio sobre el lote).<br>
4- Maneje casos borde: predicciones perfectas, predicciones muy erróneas.<br>
5- Utilice operaciones vectorizadas de NumPy (evite bucles explícitos).<br>

### Explicación de la fundamentacion matemática
La entropía cruzada mide qué tan bien le está yendo al modelo al asignarle probabilidad a la respuesta correcta. Si le da una probabilidad alta, el error es pequeño; si le da una probabilidad baja, el error es grande.<br>

En un problema de clasificación, el modelo produce una distribución de probabilidades:<br>

$$
p = [p_1, p_2, \dots, p_C]
$$

Por otro lado, la respuesta real se representa como un vector one-hot, donde toda la probabilidad está en la clase correcta. Para una sola muestra cuya clase verdadera es $y_i$, la entropía cruzada se define como: <br>

$$
H(p, y_i) = -\log(p_{i, y_i})
$$

Esto significa que solo importa la probabilidad que el modelo le da a la clase correcta.<br>

Cuando tenemos N muestras, se calcula el promedio de la pérdida como:<br>

$$
Loss = -\frac{1}{N} \sum_{i=1}^{N} \log(p_{i,y_i} + \epsilon)
$$

donde: - $p_{i,y_i}$ es la probabilidad asignada a la clase correcta en la muestra $i$. Por otro lado, $\epsilon$ es un valor pequeño (por ejemplo $10^{-9}$) que se agrega para evitar calcular $\log(0)$. Es importante resaltar que si $p_{i,y_i} = 1$, entonces $-\log(1) = 0$, lo que significa que no hay error. En cambio, si $p_{i,y_i}$ se acerca a 0, entonces $-\log(p_{i,y_i})$ crece hacia infinito, lo que implica un error muy grande. <br>

Por eso, la entropía cruzada castiga fuertemente cuando el modelo se equivoca con mucha seguridad, y recompensa cuando acierta con alta probabilidad, ayudando a que el modelo mejore sus predicciones.<br>

### Explicación del código
La implementación está pensada para ser eficiente usando operaciones vectorizadas, lo que permite trabajar con muchos datos al mismo tiempo sin usar ciclos for, según la sugerencia que dio el módulo de evitar loops explícitos. Primero, se maneja la estabilidad numérica definiendo una constante eps = 1e-9. Esto se hace para evitar calcular log(0), ya que ese valor no está definido y causaría errores. Esto se incluye según la sugerencia que dio el módulo de agregar un épsilon dentro del logaritmo.<br>
Luego, para obtener las probabilidades correctas, en lugar de recorrer la matriz fila por fila, se utiliza indexación avanzada con probs[np.arange(N), targets]. Esto permite extraer directamente, de cada fila, la probabilidad que corresponde a la clase real, según la sugerencia que dio el módulo de usar indexación avanzada. Después, se calcula la pérdida aplicando np.log() a esas probabilidades y luego np.mean() para obtener el promedio del logaritmo negativo, siguiendo la fórmula $-\frac{1}{N}\sum \log(p_{i,y_i})$ de forma vectorizada. Finalmente, la función devuelve un solo número (float) que representa la pérdida promedio del modelo en el conjunto de datos.<br>



In [11]:
import numpy as np

def cross_entropy_loss(probs: np.ndarray, targets: np.ndarray) -> float:
    # Convertir a arrays de NumPy por si vienen como listas (ejemplo 2)
    probs = np.array(probs)
    targets = np.array(targets)

    # definimos un épsilon pequeño para evitar que el log(0) dé error
    eps = 1e-9
    N = probs.shape[0]

    # Indexación avanzada solicitada en los requerimientos para extraer la probabilidad de la clase correcta
    # Esto selecciona de cada fila i el valor en la columna indicada por targets[i]
    correct_probs = probs[np.arange(N), targets]

    # Cálculo de la pérdida usando el logaritmo negativo y aplicamos la fórmula del promedio
    loss = -np.mean(np.log(correct_probs + eps))

    return float(loss)


# Se prueba el ejemplo 1
probs = np.array([[0.1, 0.9], [0.8, 0.2]])
targets = np.array([1, 0])
print(cross_entropy_loss(probs, targets))

# Se prueba el ejemplo 2
probs = [[0.9, 0.1], [0.2, 0.8]]    
targets = [1, 0]
print(cross_entropy_loss(probs, targets))


0.16425203230546248
1.956011495214073


# Ejercicio 15: Estabilidad Numérica (Log-Sum-Exp) 
Implemente una función llamada log_sum_exp(x) que calcule el logaritmo de la suma de exponenciales $\log(\sum e^{x_i})$ de forma numéricamente estable. La función debe recibir una matriz de forma (N,D) y aplicar el "truco del máximo" para evitar el desbordamiento (overflow) que ocurre al elevar números grandes a una potencia exponencial. La operación debe realizarse de forma independiente para cada fila, reduciendo la última dimensión para devolver un vector de tamaño (N).<br>

*Requerimientos*<br>
1- Implemente la versión numéricamente estable utilizando el truco de la resta del máximo.<br>
2- Calcule log-sum-exp independientemente para cada fila (reduzca a lo largo de la última dimensión).<br>
3- Devuelva un vector de forma (N,).<br>
4- Maneje casos borde: todos ceros, valores muy grandes, valores muy pequeños.<br>
5- Utilice operaciones de NumPy para computación vectorizada.<br>
6- Asegure la estabilidad numérica para cualquier rango de entrada.<br>

In [5]:
# Este es el bloque de codigo del ejercicio 15. 